tests/test.py

meet this error on debian:jessie virtual machine but never met on host machine when ran tests locally

add handling exception when pid not found

---

Makefile

unify makefile: add `install`, `install_all`, `test_all` commands
similar to
https://github.com/cossacklabs/themis/pull/248

unify makefile

---

Makefile

1. Changed unusual install path to `/usr/bin`.
2. Removed unused `install_all` target.

Changed install path to `/usr/bin`. Removed `install_all` target.

---

Makefile

Remove obsolete dependency libssl1.0.2 for debian stretch which was required by libthemis < 0.10.0.

Remove obsolete libssl1.0.2 dependency

---

cmd/acraserver/acraserver.go
cmd/acraserver/client_commands_session.go
cmd/acraserver/client_session.go
cmd/acraserver/listener.go

* drop creation new keystore in server constructor
* drop redundant session fields. now session implemented via connection wrappers

use one global keystore

---

tests/test.py

python raise an exception on os.kill when a process with such pid not exists (it may be when process.terminate was successful) so handle this case

move process.kill into try/except

---

cmd/acra_addzone/acra_addzone.go
cmd/acra_configui/acra_configui.go
cmd/acra_genkeys/acra_genkeys.go
cmd/acra_genpoisonrecord/acra_genpoisonrecord.go
cmd/acra_rollback/acra_rollback.go
cmd/acraproxy/acraproxy.go
cmd/acraserver/acraserver.go
cmd/utils.go
configs/acraproxy.yaml
configs/acraserver.yaml
logging/log_formatters.go
logging/logging.go
utils/logging.go
utils/version.go

First changes in new logging.
1.  now have new config variable that allows to customize log format
`logging_format: plaintext` | `logging_format: json` | `logging_format: cef`
2. on `main()` customize Logger according to `logging_format`
3. CEF format is not well-implemented yet, I've added interface that works similar to TextFormatter
4. Each log contains required fields (as discussed in T376): msg, severity, timestamp, product, version.
1. new `logging` package created
2. `SetLogLevel` moved to `logging` from `cmd`
3. `version.go` file created
JSON:
```
API server listening at: 127.0.0.1:60083
{"msg":"changed logging format to json","product":"acraserver","severity":"info","timestamp":"2018-03-14T18:02:09.495669863+02:00","version":"0.76"}
{"code":"123","msg":"log with …
```

custom logging 101

---

cmd/acraproxy/acraproxy.go
cmd/acraserver/acraserver.go
logging/cef_formatter.go
logging/cef_formatter_test.go
logging/log_formatters.go
logging/logging.go

1. Is compliant to [CEF spec](https://kc.mcafee.com/resources/sites/MCAFEE/content/live/CORP_KNOWLEDGEBASE/78000/KB78712/en_US/CEF_White_Paper_20100722.pdf), except extension dictionary fields. Currently we allow using any extension field names.
2. Added `unixTime` field to every CEF log, time in millis.
3. Escaped `\t`, `\n`, `\`, `|`, `=` characters in messages.
4. Default `Signature ID` (aka `EventCode`) is `0`. Change event code by:
```
log.WithField(logging.FieldKeyEventCode, "124").Infof("log with code")
```
to get log:
```
CEF:0|cossacklabs|acraserver|0.76|124|log with code|0|unixTime=1521217206.193 
```
5. Log levels are casted to `severity` field as described in [`severityByLevel`](https://github.com/cossacklabs/acra/compare/vixentael/T496-logging-cef?expand=1#diff-4c8beb689181dfc …

logging in CEF format

---

tests/test.py

Fix integration tests for `acra_rollback` tests in SSL enabled mode.
To manually run integration test if server is configured to use SSL:
```
TEST_TLS=on TEST_SSL_MODE=require TEST_DB_HOST=127.0.0.1 TEST_DB_USER=postgres TEST_DB_USER_PASSWORD=postgres TEST_DB_NAME=postgres TEST_DB_PORT=5432  python3 tests/test.py
```
Internal discussion, including buildbot reports:
https://ph.cossacklabs.com/T521

Fix test_rollback in integration test suit (T521)

---

tests/test.py

should fix errors with test on "close connections" on buildbot.  it was because was used 'require' as default value for sslmode when connection using pure driver and not used global value from env variables

use correct ssl mode for "close connections" test

---

.circleci/integration.sh
cmd/acra_configui/acra_configui.go
cmd/acraproxy/acraproxy.go
cmd/acraserver/acraserver.go
cmd/acraserver/client_commands_session.go
cmd/acraserver/client_session.go
cmd/acraserver/listener.go
cmd/utils.go
configs/acra_configui.yaml
configs/acraproxy.yaml
configs/acraserver.yaml
decryptor/mysql/decryptor.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
keystore/server_keystore.go
logging/event_codes.go
logging/log_formatters.go
logging/logging.go
network/secure_session_wrapper.go
tests/test.py

Made logging for acra_proxy, acra_server, acra_configui more user-friendly.
0. Add custom logging format for acra_configui.
1. Suggest using error codes to differentiate errors.
2. Use error codes for most logs.
3. Add more info/debug logs.
4. Unify logs language.

More logs for acra_proxy, acra_server, acra_configui

---

network/tls_wrapper.go

SystemCertPool has next code:
```
func loadSystemRoots() (*CertPool, error) {
roots := NewCertPool()
var firstErr error
for _, file := range certFiles {
data, err := ioutil.ReadFile(file)
if err == nil {
roots.AppendCertsFromPEM(data)
return roots, nil
}
if firstErr == nil && !os.IsNotExist(err) {
firstErr = err
}
}
for _, directory := range certDirectories {
fis, err := ioutil.ReadDir(directory)
if err != nil {
if firstErr == nil && !os.IsNotExist(err) {
firstErr = err
}
continue
}
rootsAdded := false
for _, fi := range fis {
data, err := ioutil.ReadFile(directory + "/" + fi.Name())
if err == nil && roots.AppendCertsFromPEM(data) {
rootsAdded = true
}
}
if rootsAdded {
return roots, nil
}
}
return nil, firstErr
}
```
and has one case when no certs was added and 0 errors then it `return …

fix initializing cert pool

---

cmd/acraproxy/acraproxy.go

check that system has installed netstat\awk that acraproxy uses to check that connection come from another user on localhost network
now it incorrectly handle situation when netstat not installed

check netstat/awk dependencies

---

cmd/acraproxy/acraproxy.go
cmd/acraserver/acraserver.go
network/tls_wrapper.go
network/utils.go
tests/test.py

add settings that change tls authentication mode. in AcraConnector it set how it will authenticate AcraServer in tls connection, on AcraServer side it setup how it will authenticate database in tls connection
plus updated tls configuration to provide other less strict authentication methods (not authenticate client from server, require any certificate, require and check) as it implemented in other places (for examples in dbs)

add auth mode param

---

acra-censor/acra-censor_configuration_provider.go
configs/acra-censor.example.yaml

for sanity sake! :D
and because `query_capture` is name of the  [`querycapture_handler`](https://github.com/cossacklabs/acra/blob/master/acra-censor/handlers/querycapture_handler.go) itself

rename 'logger' to 'query_capture' for AcraCensor

---

Makefile
cmd/acra-keymaker/acra-keymaker.go
scripts/generate-keys.sh

* added script to generating keys and placing them into appropriate directory structure
* added `gen_keys` target in `Makefile` to run `generate-keys.sh` script with default arguments

Script to generating keys and placing them into directory structure

---

decryptor/postgresql/pg_decryptor.go

return correct ErrorResponse packet on block (https://www.postgresql.org/docs/9.3/static/protocol-message-formats.html)

return ErrorResponse on query block

---

examples/python/example_with_zone.py
examples/python/example_without_zone.py
examples/python/requirements.txt
examples/python/requirements/base.txt
examples/python/requirements/mysql.txt
examples/python/requirements/postgresql.txt

* use mysql driver too
* add argument to switch to mysql
* separate requirement files for pip, to install them both or separately
* postgresql driver set as default to leave backward compatibility all examples and docs that exists now

support mysql in python examples (T633)

---

.circleci/config.yml
acra-censor/acra-censor_test.go
acra-censor/handlers/querycapture_handler.go
cmd/acra-connector/acra-connector.go
cmd/acra-server/client_session.go
cmd/acra-server/listener.go
cmd/utils.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
network/secure_session_wrapper.go
tests/requirements.txt
tests/test.py

* support prepared statements with [binary](https://dev.mysql.com/doc/internals/en/binary-protocol-resultset.html) and [text](https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-ProtocolText::Resultset) formats of response
* test support of prepared statements with postgresql/mysql (two formats)
* fix race condition (when one goroutine close connection with secure session and second try to write/encrypt)
* increase wait time in acra-censor tests for correct running on slow machines (need refactoring in a future)
* small refactoring

mysql prepared statements

---

acra-censor/acra-censor_interfaces.go
acra-censor/acra-censor_test.go
acra-censor/handlers/handlers_util.go
acra-censor/handlers/querycapture_handler.go
logging/event_codes.go

As we discussed previously having large JSON file as Query blob might be not the best option [T605]
- format changed from large json to multiline json
- on each parsed query remember query in the buffer
- dump buffer into file once a while (instead of writing into the file on each query)

Using JSON line format for QueryCapture

---

acra-censor/acra-censor_configuration_provider.go
acra-censor/acra-censor_implementation.go
acra-censor/acra-censor_test.go
acra-censor/handlers/blacklist_handler.go
acra-censor/handlers/handlers_util.go
acra-censor/handlers/querycapture_handler.go
acra-censor/handlers/whitelist_handler.go
configs/acra-censor.example.yaml

now user can configure to not block queries that censor can't parse via parameter in censor config `ignore_parse_error` that default `false` (parsing with errors will block queries as default)

ignore parse errors

---

logging/log_formatters.go
tests/test.py

set unixtime to new copy of fields instead of formatter's field that is global for each `format` call. 
We had situation:
1. goroutine1 lock mutex, update time in formatter's `Fields` 
2. goroutine2 blocked after trying to lock mutex
3. goroutine1 unlock mutex, execute code and start to iterate over `Fields` and copy values (in `copyEntry` function)
4. goroutine2 unblocked and update time in formatter's `Fields` 
5. goroutine1 on next iteration see that map was changed and is not "fresh", and panic

fix concurrent map iteration during logging

---

cmd/acra-reader/server.go
logging/event_codes.go

Initial version of AcraReader HTTP API handling.
API format:
Request
```
POST `<host>/v1/decrypt?zone_id=<zone_id_string>`
Content-Type: application/octet-stream
Content-Length: [NUMBER_OF_BYTES_IN_FILE]
[ACRASTRUCT]
```
Response:
```
HTTP/1.1 200 OK
Content-Length: 88
Content-Type: application/octet-stream
Connection: Closed
[DECRYPTED ACRASTRUCT]
```

[WIP] AcraReader: basic HTTP API /decrypt handling

---

.circleci/config.yml
.circleci/integration.sh

use one gopath for all versions of golang and download sources of dependencies once
p.s. actually, it decreases duration of this operations from ~1.5-2 minutes to 0.7-1 min ... Depends on network

speedup circleci

---

cmd/acra-rollback/acra-rollback.go
tests/test.py

after recent acra-rollback usage met case when it was helpful if acra-rollback check that query contains expected placeholder for example if user run from bash like: 
``` 
acra-rollback arg1 arg1 --insert="some query $1" 
``` 
he will be surprised to see that output will not contain any decrypted data but `select` queries and decryption was executed. Because bash use `$n` as placeholders too :)
acra-rollback will take query with replaced value by bash (empty for example and placeholder will not placed in query)

check that insert query contain placeholder

---

acra-censor/acra-censor_test.go
acra-censor/handlers/querycapture_handler.go

Clean up "ghost" censor_log file that appears after AcraCensor unit tests.

Fix AcraCensor tests

---

cmd/acra-server/acra-server.go

I think we get mysterious panics in tests because after `go server.Start()` golang runtime can free server struct in some cases because in main function it doesn't used after this function call and to be sure I want to try explicitly say to keep alive this struct

avoid free server struct until end of program [T707]

---

docker/README.md
docker/docker-compose.translator-ssession-connector-grpc.yml
docker/docker-compose.translator-ssession-connector-http.yml
tests/generate_acrastruct.py
tests/utils.py

* created docker-compose examples:
- `docker/docker-compose.translator-ssession-connector-grpc.yml`
- `docker/docker-compose.translator-ssession-connector-grpc.yml`
* written small script `tests/generate_acrastruct.py`
* added optional argument `keys_dir` to `read_storage_public_key` method

Created AcraTranslator examples

---

.circleci/check_golint.sh
.circleci/config.yml
acra-censor/handlers/blacklist_handler.go
acra-writer/acra-writer.go
cmd/acra-authmanager/acra_authmanager.go
cmd/acra-server/auth.go
cmd/acra-server/config.go
cmd/acra-translator/grpc_api/decryptor.go
cmd/acra-webconfig/acra-webconfig.go
decryptor/mysql/utils.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/pg_escape_decryptor.go
decryptor/postgresql/pg_general_decryptor.go
decryptor/postgresql/pg_hex_decryptor.go
fuzz/fuzz.go
keystore/filesystem/connector_keystore.go
network/raw_wrapper.go
network/secure_session_wrapper.go
network/tls_wrapper.go
utils/utils.go
zone/byte_reader_binary.go
zone/byte_reader_pg_escape.go
zone/byte_reader_pg_hex.go
zone/matcher.go
zone/matcher_pool.go
zone/zone_id_matcher.go

- More comments.
- Fix errors naming.
- Small fixes here and there.
- Enable golint checks on CircleCI. Builds will fail if amount of issues will be more than 250.
Current amount of issues: 241.
Basically, most issues that are left connected with:
- names of constants ("don't use ALL_CAPS in Go names; use CamelCase" -> 219 issues)
- name of packages ("don't use an underscore in package name" -> 8 issues)
As soon as we don't want to change constants style, I think we're done with golint fixing for now.

More golint fixes

---

acra-censor/acra-censor_configuration_provider.go
acra-censor/acra-censor_interfaces.go
acra-censor/acra-censor_test.go
acra-censor/handlers/blacklist_handler.go
acra-censor/handlers/handlers_util.go
acra-censor/handlers/whitelist_handler.go
cmd/acra-server/config.go
configs/acra-censor.example.yaml
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
tests/acra-censor_configs/acra-censor_blacklist.yaml
tests/acra-censor_configs/acra-censor_whitelist.yaml

1) Add support of %%SELECT%%
2) Add support of SELECT %%COLUMN%% .. %%COLUMN%%
3) Add support of SELECT A,B FROM T %%WHERE%%
I added some stubs (commented some places in code) to whitelist workflow - would like to know from reviewers if blacklist now will work as expected

Add some patterns support to blacklist [T660]

---

cmd/acra-connector/acra-connector.go
cmd/acra-server/acra-server.go
cmd/acra-server/listener.go
cmd/acra-translator/acra-translator.go
cmd/acra-translator/grpc_api/decryptor.go
cmd/acra-translator/server.go
configs/acra-connector.yaml
configs/acra-server.yaml
configs/acra-translator.yaml

While polishing documentation, I found and fixed these issues:
- ATran: fix poison records callback order – first handle script, then shutdown.
- update user-friendly descripton for poison records params AS/ATran
- return Poison Record decryption error for gRPC connection of ATran
- fix naming and logs here and there
- re-generate configs

Small fixes of poison records handling

---

acra-censor/acra-censor_test.go
acra-censor/handlers/handlers_util.go

1) Add ' * ' support in pattern
2) Update handling of *ComparedExprs values
3) Add tests for whitelist and blacklist

Improve %%VALUE%% pattern

---

acra-censor/acra-censor_implementation.go
acra-censor/acra-censor_test.go
acra-censor/handlers/blacklist_handler.go
acra-censor/handlers/handlers_util.go
acra-censor/handlers/querycapture_handler.go
acra-censor/handlers/queryignore_handler.go
acra-censor/handlers/whitelist_handler.go
cmd/acra-server/listener.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
tests/acra-censor_configs/acra-censor_blacklist.yaml
tests/acra-censor_configs/acra-censor_whitelist.yaml
tests/test.py

1. **QueryCaptureHandler** was storing in the `query_capture` log file redacted queries (which is good), but was comparing non-redacted queries during `CheckQuery` (which is bad and leads to duplication of the same redacted queries in the `query_capture` log file). 
**Fixed:** now QueryCaptureHandler uses redacted queries for checking and writing/reading from `query_capture` log file.
2. **QueryCaptureHandler** used `IsForbidden` as keyword for queries-that-should-be-blocked-some-day-via-WebConfig, which lead to users confusion (because `IsForbidden` doesn't indicate state of query after passing the AcraCensor).
Numerous tests were updated to handle multiple cases and redacted queries.renamed to `_blacklisted_by_web_config ` which indicates that this is private field and points on its …

AcraCensor: normalize queries and fix QueryCaptureHandler

---

acra-writer/acra-writer.go
wrappers/nodejs/acrawriter.js
wrappers/objc/AcraWriter/AcraWriter.m
wrappers/ruby/acrawriter/lib/acrawriter.rb

According to @secumod comments, I've added zeroing of symmetric key and keypair private key to most of acra-writer wrappers (excluding php).
I've run acra-writer tests manually to make sure the syntax is correct and tests are succeed.

Zeroing private keys in acrawriters

---

acra-censor/acra-censor_implementation.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
logging/logging.go

Log queries during decryption by AcraCensor if enabled, or only in Debug mode.
Actually, this is an attempt to optimize too often usage of `NormalizeAndRedact` function.

Remove repetitive and redundant logs

---

acra-censor/acra-censor_test.go
acra-censor/handlers/handlers_util.go
network/secure_session_wrapper.go
utils/utils.go

added validation of first packet from acra-connector to acra-server that send before secure session packets and has limited length that we can check (client id can have 255 symbols as length plus some overhead with length of packet). set 1kb limit
p.s. plus found old local code with extended tests for acra-censor that forget to add to some previous pr. added to this pr because not so much and simple changes

validate clientid packet length [T696]

---

cmd/acra-connector/acra-connector.go
cmd/acra-connector/connector-mode/connector-mode.go
decryptor/postgresql/packet_handler.go
decryptor/postgresql/packet_handler_test.go
decryptor/postgresql/pg_decryptor.go
network/proxy.go
tests/test.py
utils/utils.go

postgresql has 3 special message types that has format another than all other message: startup, ssl request and cancelation request. 
before we try to parse only first packet as special and all other as general
but was case when client send ssl request (first special), then if it continue after db response it send startup message. we correctly handle case when db accept ssl request and didn't handle deny from db.
Now processing re-writed for client's side of processing and we try to recognize these special messages or other known general messages and doesn't depend on their order (first, second etc). Plus in a future can process them separately. 
plus added handling columns with null values (it fixes panics [T790])

refactor processing clients packets

---

cmd/utils.go
configs/acra-addzone.yaml
configs/acra-authmanager.yaml
configs/acra-connector.yaml
configs/acra-keymaker.yaml
configs/acra-poisonrecordmaker.yaml
configs/acra-rollback.yaml
configs/acra-rotate.yaml
configs/acra-server.yaml
configs/acra-translator.yaml
configs/acra-webconfig.yaml

in a past was added logic to generate description of cli args in markdown format as table and was leaved as is with hardcoded paths. It was used for our documentation in a past
I refactored it. Let discuss do we need it now and do we want to add it to repo

Add parameter to generate CLI agrs in markdown

---

acra-censor/handlers/common.go
acra-censor/handlers/handlers_util.go
acra-censor/handlers/handlers_util_test.go

* support `WHERE age = (%%SUBQUERY%%)` that should match condition like `WHERE age=(select 12)` or `WHERE age=(select age from table1 union select age from table2)`
* support `WHERE age in (%%VALUE%%, %%VALUE%%)` - `WHERE age in (1, 'some string value')`
* support `WHERE age in (%%LIST_OF_VALUES%%)` - `WHERE age in (1, TRUE, FALSE, 'string')`
* support `WHERE age in (%%SUBQUERY%%)` - `WHERE age in (select age from table1)`
* support different variants like `WHERE column in (%%VALUE%%, 'special string' (%%SUBQUERY%%), %%LIST_OF_VALUES%%)` - `WHERE column in ('any value', 'special string', (select 1), 'val1', 'val2', 'val3')`
Notes:
* %%SUBQUERY%% placeholder should be wrapped with parentheses
* %%LIST_OF_VALUES%% expect at least 1 any value at the same place of query

support sql IN clause in acra-censor [T815]

---

acra-censor/handlers/common.go
acra-censor/handlers/handlers_util.go
acra-censor/handlers/handlers_util_test.go

* support `WHERE a=(%%SUBQUERY%%)` - `WHERE a = (select 1)`
* support `WHERE a BETWEEN (%%SUBQUERY%%) and %%VALUE%%` - `WHERE a BETWEEN (select 1) and 'some value'`
* support `WHERE EXISTS(%%SUBQUERY%%)`

support subquery in range comparison [T815, T817]

---

cmd/acra-connector/acra-connector.go
cmd/acra-rotate/acra-rotate.go
cmd/acra-rotate/dbRotation.go
cmd/acra-rotate/fileRotation.go
cmd/acra-rotate/rotator.go
cmd/acra-translator/grpc_api/api_test.go
cmd/acra-translator/http_api/mock_keystorage.go
cmd/acra-translator/server.go
decryptor/mysql/decryptor_test.go
keystore/filesystem/server_keystore.go
keystore/filesystem/server_keystore_test.go
keystore/keystore.go
tests/test.py
zone/zone_id_matcher_test.go

`acra-rotate` with flag `--dry-run` will fetch acrastructs (from files or database), decrypt, rotate in memory keys, encrypt with new public keys and print result json with new public keys without saving rotated keys and acrastructs (to filesystem or database)

dry run rotate [T813]

---

.circleci/config.yml
cmd/acra-rollback/acra-rollback.go
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
keystore/lru_cache/lru_cache.go

* noticed that lru cache doesn't guarantee safe concurrent access. added mutex https://github.com/golang/groupcache/blob/master/lru/lru.go#L22
* use formatted logging functions when used placeholders in text

add concurrent access in lru cache

---

.circleci/config.yml
logging/log_formatters.go

check that entry hasn't timestamp and only then add it before logging to not override timestamp if it was set before
use case: code that collect some log entries with timestamps before export and periodically print/export it. so now if code collect log entries with correct timestamps then logger will override it

log timestamp.Now only if not set

---

cmd/acra-connector/acra-connector.go
cmd/acra-server/acra-server.go
cmd/acra-server/client_commands_session.go
cmd/acra-server/client_session.go
cmd/acra-server/config.go
cmd/acra-server/listener.go
cmd/acra-server/prometheus.go
cmd/acra-translator/acra-translator.go
cmd/acra-translator/config.go
cmd/acra-translator/server.go
decryptor/mysql/decryptor.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/packet_handler.go
decryptor/postgresql/packet_handler_test.go
decryptor/postgresql/pg_decryptor.go
keystore/filesystem/server_keystore.go
logging/event_codes.go
logging/log_formatters.go
logging/trace.go
network/connection_wrapper.go
network/connection_wrapper_test.go
network/proxy.go
network/raw_wrapper.go
network/secure_session_listener.go
network/secure_session_wrapper.go
network/tls_wrapper.go
network/trace.go
tests/test.py

* extend connection wrapper with new context.Context parameter
* use specific logger instead global when it exists
* send trace data from connector to server/translator
* receive trace data on translator for http requests (grpc now unsupported because need deeper integration)
* receive trace data on server side and use it to create next spans
* add log exporter of traces
* add parameters for jaeger exporter

add tracing with opencensus

---

.circleci/config.yml

grpc-go removed support of go 1.6-1.8 - https://github.com/grpc/grpc-go/commit/59a2cfbdf9272f6334fe4856b6e7c8d212845b3d
and after that, we have failed tests

drop go18 support

---

decryptor/mysql/response_proxy.go
decryptor/postgresql/packet_handler.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/utils.go
decryptor/postgresql/utils_test.go
tests/requirements.txt
tests/test.py

noticed that now we don't process queries from prepared statements in binary protocol to postgresql with acra-censor (decryption worked before)
but can't add good integration tests now, because python hasn't good libraries to work with postgresql with binary protocol. psycopg2 (most popular) use text protocol for prepared statements (that we test too). found asyncpg, but tests with it unstable in my local environment (tests fail on closing connection or unexpected empty result without any errors)
now tested it manually before push and check that branch of fetching query from Parse packet works as expected and leave tests with asyncpg which can be used by commenting `self.skipTest` in `checkSkip` function

process queries in prepared statements in binary protocol (pgsql)

---

cmd/jaeger.go
cmd/tracing.go
configs/acra-connector.yaml
configs/acra-server.yaml
configs/acra-translator.yaml

to avoid misconfiguration we with @shadinua decided that would be better to remove default values and require the explicit setup of this params

remove default endpoints for jaeger trace exporter

---

acra-censor/acra-censor_implementation.go
acra-censor/handlers/blacklist_handler.go
acra-censor/handlers/queryignore_handler.go
acra-censor/handlers/whitelist_handler.go
decryptor/mysql/response_proxy.go
tests/acra-censor_configs/acra-censor_blacklist.yaml
tests/acra-censor_configs/acra-censor_whitelist.yaml
tests/test.py
tests/utils.py

* add usage of prepared statements in acra-censor tests and refactored connections to re-use the same code (connections with different drivers and text/binary prepared statements per db type) in several places 
* add query as is if can't normalize to QueryIgnore handler to allow ignore queries that can't parse

test prepared statements with acra-censor

---

decryptor/postgresql/packet_handler.go
tests/test.py

* fixed counting result length of packet
* added usage of null columns in tests to meet such errors in the future

correctly handle null values in columns

---

examples/cpp/Readme.md
examples/cpp/main.cpp
examples/cpp/main_tests.cpp

Hi there, cppcodec maintainer here. Thanks for using my library!
I released the 0.2 version a few months ago, which include a note that `*_default_*.hpp` includes are not recommended anymore and may be discontinued in the future. Not sure how popular your software is, but if you're going through the trouble of writing tutorials of your own, I think maybe I should try to update your examples, so people adopt the "right" way of doing things after looking at your README.
The good news is that you've already been using your own alias statements, like here:
```
using base64 = cppcodec::base64_rfc4648;
using hex = cppcodec::hex_lower;
```
The types on the right hand are provided by the header files of the same name, no `*_default_*` ones are required and the only change I'd make is adapting the …

Adapt cppcodec usage to current recommendations

---

examples/cpp/Readme.md
examples/cpp/libs/cppcodec/base32_hex.hpp
examples/cpp/libs/cppcodec/data/raw_result_buffer.hpp
examples/cpp/libs/cppcodec/detail/stream_codec.hpp
examples/cpp/main.cpp
examples/cpp/main_tests.cpp

As next step of #289 I've update the source code of cppcodec as well. We link cppcodec as source code in AcraWriter C++ example, so I've updated the entire "libs/cppcodec" folder.
Thank you @jpetso!

Update version of cppcodec for AcraWriter C++ example project

---

acra-censor/acra-censor_configuration_provider.go
acra-censor/acra-censor_implementation.go
acra-censor/acra-censor_interfaces.go
acra-censor/acra-censor_test.go
acra-censor/common/common.go
acra-censor/common/matching_logic.go
acra-censor/common/matching_logic_test.go
acra-censor/handlers/blacklist_handler.go
acra-censor/handlers/querycapture_handler.go
acra-censor/handlers/queryignore_handler.go
acra-censor/handlers/whitelist_handler.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go

1) Move common table matching logic from whitelist/blacklist handlers;
2) Fix parsing error logic
3) Some refactoring

Censor fixes

---

decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
tests/generate_acrastruct.py

prevent decryption unexpected result with \0\0\0 values without correct encoding

encode data to bytes in tests/generate_acrastruct.py

---

tests/requirements.txt
tests/utils.py

pyyaml uploaded to PYPI only 3.13 version so changed dependency to use directly sources from github instead PYPI until they update their package in PYPI
anyway we use this library only for tests and parse our static file from our repo and this fix just to hide alert from github : )

use newer version of pyyaml due to CVE-2017-18342

---

decryptor/postgresql/dataProcessor.go
encryptor/config/tableSchema.go
encryptor/queryDataEncryptor.go
logging/log_formatters.go
utils/dbByteArrayEncoders.go

* make public `GetTablesWithAliases` function (was method) and `AliasedTableName` to reuse it in enterprise code 
* fix govet, use pointer to struct with sync.Once - https://goreportcard.com/report/github.com/cossacklabs/acra
* return decrypted string as is without encoding to hex if it simple string. it reduces length of packet

public methods to extract table aliases from query

---

acra-censor/common/logging_logic_test.go

While debugging censor's logging logic I occasionally commented this test. Now its time to restore it. Sorry, my fault

fix occasionally commented censor's query capture test

---

decryptor/base/observers.go
decryptor/mysql/proxy.go
decryptor/mysql/proxy_test.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/proxy.go
decryptor/postgresql/proxy_test.go
encryptor/config/tableSchema.go

don't initialize encryptor if config is empty and do not add it to OnQuery observers. it helps to avoid extra parsing of incoming queries

correctly turn off encryptor

---

tests/test.py

fix incorrect placeholder. `logger.info`  expects `%s` placeholders but used `{}` that allowed by `str.format` method. Added `str.format` usage to fix errors.

correct string formatting

---

acra-censor/common/logging_logic.go
acra-censor/common/logging_logic_test.go
acra-censor/handlers/querycapture_handler.go
tests/test.py

found that when censor starts and read existing queries from disk he doesn't update queryindex and work with queryindex == 0. and then after serialization timer's tick it dump buffered queries that was appended (all queries stored in handler.Queries array after queryindex position that store index of last dumped query). And it dump all queries loaded at start and only after that update queryindex to correct value `Length(loadedQueries)`.

fix querycapture duplicate logs

---

.gitignore
cmd/acra-connector/acra-connector.go
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
utils/version.go

added logging version at start. it looks now like that:
```
INFO[0000] Starting service acra-server [pid=591]        version=0.84.2
INFO[2019-02-21T14:46:00+02:00] Validating service configuration...
...
```

print version on start

---

cmd/acra-connector/prometheus.go
cmd/acra-server/prometheus.go
cmd/acra-translator/common/prometheus.go
cmd/acra-translator/prometheus.go
cmd/prometheus.go
tests/requirements.txt
tests/test.py
utils/version.go

* export `<service_name>_version_major`, `<service_name>_version_minor`, `<service_name>_version_patch` metrics where <service_name> replaced with _acraserver_ | _acraconnector_ | _acratranslator_ (all services that works as daemon)
* renamed _translator_request_processing_seconds_ -> _**acra**translator_request_processing_seconds_ metric name according to other metrics name
* updated tests that should check that all expected metrics exported and check that they have any value where it possible

export version as metric

---

acrawriter.podspec
examples/objc/AcraWriterUsage.xcodeproj/project.pbxproj
examples/objc/AcraWriterUsage/AppDelegate.m
examples/objc/Podfile.lock

Similar fix as in Themis (https://github.com/cossacklabs/themis/pull/407/), update `acrawriter.podspec` to use more correct (and device-compatible) settings for bitcode.

Update acrawriter.podspec for iOS to handle correct bitcode

---

wrappers/objc/AcraWriter/AcraWriter.m

Themis `0.10.4` brings modular frameworks on Swift, which has changed a bit a way how it's imported inside AcraWriter module.
New acrawriter.podspec is coming after merging this PR.

Update acrawriter to import Themis in a new way

---

wrappers/objc/AcraWriter/AcraWriter.m

It's something weird going on, podspec from #325 can't pass validation with new header. I believe it's connected with HEADER_SEARCH_PATH, Swift frameworks and all the magic Xcode makes out-of-the-box.
So I revert this change, and move `HEADER_SEARCH_PATH` back to the podspec.
Sorry for the mess.

Revert #324

---

cmd/acra-connector/prometheus.go
cmd/acra-server/prometheus.go
cmd/acra-translator/prometheus.go
cmd/prometheus.go
tests/test.py
utils/version.go

export `acra[server|connector|translator]_build_info` metric with two labels:
* version - with @shadinua we discussed that it will be useful too to have metric in such format and it's a convenient way to export it and used in other libraries (ex: prometheus' golang client library)
* edition[ce|ee]
plus I merged exporting static values as metrics (version major/minor/patch parts) with registering them. because they should be used only once and it unnecessary to split it to two explicit calls

export edition and version as build_info

---

tests/test.py

small refactoring that allow to re-use generated zones from ACE integration tests in AEE tests.
If AEE tests will import some TestCase from ACE and `zones` global variable with pre-generated values, then `unittest` module will call `setUpModule` + `tearDownModule` for ACE tests initialization and once `setUpModule` for AEE tests that call base `setUpModule`. `zones` will contain all zones that was generated in `setUpModule` for ACE but files that store keys will be deleted in `tearDownModule`. But `zones` variable wasn't updated after deletion and AEE will try to use not-existing keys from first generation

remove side effect from re-using generated zones in other test modules

---

cmd/acra-connector/acra-connector.go
cmd/acra-server/config.go
tests/test.py

in one recent refactoring I broke fetching acraserver configuration via acra-webconfigui and @shad met this bug
AcraServer returned his host/port values that it listen instead db host/port. Now it fixed and updated tests that should catch such errors.

fetching configuration via webconfig [T1099]

---

.circleci/prepare.sh

new version pip has some conflicts and some people fix it with binding last correct pip version until it will be fixed

install correct pip and libpq-dev to build python dependencies

---

.circleci/config.yml
.circleci/integration.sh
.circleci/prepare.sh
tests/acra-censor_configs/acra-censor_whitelist.yaml
tests/requirements.txt

Integration tests failed due to 2 problems:
* compilation binaries as startup
* sqlalchemy and his drivers to mysql/mariadb added new and changed old queries which they send to db before executing users query (like setup correct charset, fetch some db metadata, default transaction mode, etc) and they are not in our whitelist config which used in tests and censor drop connection with database (as it should be when he doesn't know these queries : )
When we added module support golang need more time to fetch all dependencies
Our integration test compile all needed binaries at start and then use them and has timeout 2 minutes
Now compilation with fetching dependencies sometimes takes more than 2min and raise exception.
**Solution:**
* Added fetching all dependencies before running test
* …

Fix integration tests [T1353]

---

decryptor/mysql/decryptor.go
decryptor/postgresql/pg_decryptor.go
tests/test.py

previously when acra didn't find acrastruct signature it didn't flush remaining part of plaintext
so when acra process block of data like `<plaintext1> <acrastruct> <plaintext2>` it return `<plaintext1> <decrypted>` and drop last `<plaintext2>`
this pr fix this problem for pgsql/mysql protocols and add tests which should detect it in a future
plus I met flapping test case with prometheus metrics when connection processing on acra-translator was so fast that it didn't increase sum value... so set it to 0

fix injected mode with plaintext at end of data

---

decryptor/postgresql/utils.go
decryptor/postgresql/utils_test.go

end of Parse packet has 2 bytes for count of parameters and sequence of 4 byte parameters
our code didn't read these parameters. it's read 1 byte of param count and +3 bytes of first parameter and do it in loop *( 
it wasn't catched because these part tested only in our integration tests and drivers which we use for that doesn't describe parameters types explicitly.
I copied one example of such packet as fixture for unit test. because we don't need any generator for such packets and we pass this data as is so we can't programmatically generate such packets for tests

fix parsing Parse packet for pgsql protocol

---

docker/acra-build.dockerfile

Earlier, we changed the prefix of paths where Themis installed when building from sources. Now it is `/usr/local/lib/` instead of `/usr/lib/`. But in the case when we build a new docker image from scratch which does not include system configuration files, libraries cannot be found.
Let's install Themis from packages into build image and always use `stable` branch regardless of the Acra branch.

Fix themis dependency in the docker image

---

cmd/acra-migrate-keys/acra-migrate-keys.go
configs/acra-migrate-keys.yaml
configs/regenerate.sh
keystore/filesystem/filenames.go
keystore/filesystem/key_export.go
keystore/filesystem/server_keystore.go
keystore/filesystem/server_keystore_test.go
keystore/v2/keystore/importV1.go
keystore/v2/keystore/importV1_test.go
keystore/v2/keystore/keyRingUtils.go
keystore/v2/keystore/poison.go
keystore/v2/keystore/webConfig.go
tests/test.py
utils/utils.go
utils/utils_test.go

Create a tool for migrating keys between key store formats. Currently it supports only v1 ⟹ v2 migration.
With default settings it is enough to simply run `acra-migrate-keys` to migrate keys from `.acrakeys` (v1) into `.acrakeys.migrated` (v2). After successful migration the administrator has to manually reconfigure Acra services to use the new key store. It is possible to explicitly specify migration details via `--src...` and `--dst...`  options if necessary.
There is a `--dry_run` option which performs migration in memory, without writing results to disk. You can use it to test that everything is in place, the keys can be read and understood.
By default the migration tool will refuse to write output into already existing key store. This is because the migration process is not …

acra-migrate-keys tool

---

keystore/v2/keystore/api/key.go
keystore/v2/keystore/api/keyRing.go
keystore/v2/keystore/asn1/asn1.go
keystore/v2/keystore/filesystem/backend/api/backend.go
keystore/v2/keystore/filesystem/backend/filesystem.go
keystore/v2/keystore/filesystem/keyRing.go
keystore/v2/keystore/filesystem/keyRingTX.go
keystore/v2/keystore/filesystem/keyStore.go
keystore/v2/keystore/signature/notary.go

As much as I dislike whole code base commits, let's do it before this branch lands into master.
Update error messages used by key store v2 to conform to Go style. Remove all `KeyStore` prefixes, start the messages with a lowercase letter, and provide enough context in the message itself to see where the problem has originated.

Improve error message style (Key Store v2)

---

.circleci/config.yml
cmd/acra-read-key/acra-read-key.go
configs/acra-read-key.yaml
configs/regenerate.sh
tests/test.py
tests/utils.py

This patch series teaches CircleCI to run integration test suite with key store v2.
The test suite now reacts to the `TEST_KEYSTORE` environment variable. If it is not set or set to `v1`, the test suite runs with current key store (v1). If that variable is set to `v2`, the tests run with new experimental key store (v2). This is meant for complete integration test suite run from scratch.
The test suite has been too tightly coupled with key store v1, hardwiring the expected environment variables, key store layout and data format, etc. All of this has been abstracted out where necessary. The tests now read keys using a new **acra-read-key** tool, which currently can read storage keys (by client and zone ID) and the poison record key. It somewhat intersects with key export tool, but works …

Run integration tests with key store v2

---

keystore/v2/keystore/filesystem/backend/filesystem.go

Similar change to master: https://github.com/cossacklabs/acra/pull/367
This works for (real) filesystem key stores but may cause compatibility issues with other key-value backends if the filesystem path somehow make it to the "key" values. This can make keys inaccessible and locked into whatever absolute path was used during key generation. Remove this "fix" before the feature lands into master.
This updates only v2-specific additions. We'll pull fixes from master later.

Use key store paths as specified by user [keystore v2]

---

keystore/v2/keystore/filesystem/backend/api/backend.go
keystore/v2/keystore/filesystem/backend/api/tests/backend.go
keystore/v2/keystore/filesystem/backend/file_lock.go
keystore/v2/keystore/filesystem/backend/filesystem.go
keystore/v2/keystore/filesystem/backend/memory.go
keystore/v2/keystore/filesystem/keyStoreLoad.go

CI builds for keystore-v2 branch have been intermittently failing on the unit test for key store file locking. It turns out that synchronization is damn hard and I still have not learned how to write it correctly. This PR attempts to solve the issue that caused test failures.
BSD-style flocks are per-process. I have incorrectly assumed that these are "Linux kernel processes" (= per-thread), however this turned out to be incorrect. These locks are per-PID. Furthermore, they are recursive in a weird way: if a process requests a shared lock when holding an exclusive lock (or vice versa), the lock is transformed into the new type in a non-atomic way (that is, the lock is released and re-grabbed). And finally, goroutines do not map directly onto system threads, so even if flocks did work …

Protect key store flock with sync.Mutex

---

keystore/v2/keystore/crypto.go
tests/test.py

Keys should not be reused for multiple purposes, that's why key store v2 uses two distinct keys: one for encrypting private key data, and one for signing all key store data. Let's detect configuration errors and refuse to create or open a key store if both keys are the same.
Since the key store does not have direct access to the keys and cannot check for that, the only place where we can still do it is when the keys are retrieved from the environment. This also gives us a chance to point out to the user what exactly is wrong with the environment.

Forbid v2 master keys to be the same

---

CHANGELOG_DEV.md
Makefile
docker/_scripts/acra-build/add_component.sh
docker/_scripts/acra-build/install_go.sh
docker/acra-build.dockerfile
docker/acra-connector.dockerfile
docker/acra-keymaker.dockerfile
docker/acra-server.dockerfile
docker/acra-tools.dockerfile
docker/acra-translator.dockerfile
docker/acra-webconfig.dockerfile

* Makefile now has:
- clean, readable and maintainable structure (I hope)
- strict division by sections and namespaces
- OS detection
- correct error handling for most cases
* implemented build/install:
- build target builds the binaries in the ./build subdirectory
- install target builds and installs binaries into system/user $GOPATH directory
- test/test_all run tests
- clean removes all created artifacts
* refined packaging:
- single target pkg
- auto detection of package type
- deb and rpm targets are temporarily left for backward compatibility
- supported Debian >= 9, Ubuntu >= 16.04, RHEL >= 7, CentOS >= 7
* refined docker build flow:
- useful scripts added for easy automation
- dockerfiles refined
- labels refined
* implemented help system:
- try this: make help
- auto generated …

Improve build scripts

---

cmd/acra-connector/acra-connector.go
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
cmd/acra-webconfig/acra-webconfig.go
logging/hooks_test.go
logging/log_formatters.go
logging/logging.go

These changes are rather technical. 
Main point is soonest customization for logging process (as we discussed by voice - it is critical 1) to preserve format for logging in error cases, even if not all parameters for customization have been already loaded, and 2) to start logging only when format is customized). 
Since format is specified by actual formatter object (`CefFormatter`, `JsonFormatter`, `TextFormatter`), it is necessary to create this object first, and then to perform customization on it. For this reason - `SetFormat(*loggingFormat)` function (that previously returns nothing) is changed onto function `logging.CreateFormatter(*loggingFormat)` that returns actual formatter object with empty fields. Then, as long as parameters become ready (basically hooks and service name - …

Technical changes in logging customization

---

cmd/acra-key-tool/acra-key-tool.go
configs/acra-key-tool.yaml
keystore/filesystem/server_keystore.go
keystore/keystore.go
keystore/v2/keystore/api/key.go
keystore/v2/keystore/api/keyRing.go
keystore/v2/keystore/api/tests/keyRing.go
keystore/v2/keystore/filesystem/key.go
keystore/v2/keystore/filesystem/keyRing.go
keystore/v2/keystore/filesystem/keyRingTX.go
keystore/v2/keystore/keyRingUtils.go
keystore/v2/keystore/transport_connector.go
keystore/v2/keystore/transport_server.go
keystore/v2/keystore/transport_translator.go
tests/test.py
tests/utils.py

There were a couple of tests left out in #361. Those tests verified that Acra works as expected for unknown keys which was simulated by removing keys from the key store. Key store v1 has it easy as key files can be directly removed from the filesystem. Key store v2 is (way) more complex so you cannot just remove a key ring file. (Well, actually, you *can* right now because the key directory integrity is not verified, but this will not be the case in the future.) However, key store v2 also has a concept of a **destroyed key** – a 'zombie' key with only metadata remaining, but with no actual key material retained. We make use of it.
This patch set starts by updating the tests to decouple them from direct key store access. Instead, new utility function `destroy_key()` should be used to …

Test key removal in key store v2

---

acra-writer/acra-writer.go
acra-writer/acra-writer_test.go
cmd/acra-authmanager/acra_authmanager.go
cmd/acra-server/client_commands_session.go
decryptor/base/utils.go
decryptor/base/utils_test.go
decryptor/binary/binary_decryptor.go
decryptor/mysql/decryptor_test.go
decryptor/postgresql/pg_escape_decryptor.go
decryptor/postgresql/pg_hex_decryptor.go
encryptor/queryDataEncryptor_test.go
go.mod
go.sum
keystore/filesystem/server_keystore.go
keystore/filesystem/server_keystore_test.go
keystore/keystore.go
network/connection_wrapper_test.go
network/deadline_listener.go

GoThemis 0.12 has deprecated some API names which broke Go conventions (https://github.com/cossacklabs/themis/pull/424). Update the code to use new names.
Note that Secure Cell API is scheduled for an overhaul in the next version of GoThemis 0.13.
Also, since GoThemis 0.12 it is possible to use properly versioned modules. Update go.mod accordingly.
While I've been auditing uses of `gothemis` package I have noticed that in one place we have been erroneously using it's `errors` subpackage instead of the standard one.

Use modern GoThemis 0.12 API

---

cmd/acra-rollback/acra-rollback.go
cmd/acra-rotate/rotator.go
cmd/acra-translator/grpc_api/decryptor.go
cmd/acra-translator/http_api/decryptor.go
decryptor/base/dataProcessor.go
decryptor/base/decryptor.go
decryptor/binary/binary_decryptor.go
decryptor/mysql/decryptor.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/pg_general_decryptor.go
decryptor/postgresql/pg_hex_decryptor.go
decryptor/postgresql/proxy_test.go
keystore/filesystem/server_keystore.go
tests/requirements.txt
tests/test.py
utils/utils.go

Teach remaining services working with AcraStructs – **acra-server, acra-rollback, acra-rotate** – to use historical keys for decryption. Previously only acra-translator supported that. Now it should be truly possible to rotate keys without reencrypting the data.
While we're here, clean up key wiping as well. Now we wipe keys on acra-server as soon as we don't need them.
Tests for acra-rotate are quite involved so I do not want to copy-paste them with key rotation added. I have pulled a library for data-driven testing ([`ddt`](https://ddt.readthedocs.io/en/latest/index.html)) to cover cases with and without key rotation. It's not pretty because of some inheritance issues, but it works. @Lagovas, if you have any ideas how to make it better (ideally, without a massive refactoring), I'm all …

Support storage key rotation

---

keystore/v2/keystore/api/key.go
keystore/v2/keystore/api/keyStore.go
keystore/v2/keystore/api/tests/key.go
keystore/v2/keystore/api/tests/keyStore.go
keystore/v2/keystore/asn1/asn1.go
keystore/v2/keystore/asn1/keyStoreFormat.asn1
keystore/v2/keystore/filesystem/export.go
keystore/v2/keystore/filesystem/key.go
keystore/v2/keystore/filesystem/keyRingTX.go
keystore/v2/keystore/filesystem/keyStore.go
keystore/v2/keystore/filesystem/keyStore_test.go

This PR is work-in-progress on key export and import. Here we add low-level API for exporting and importing keys, and implement the export code path which is easier. Importing will come later as it's a bit harder. Meanwhile I'd like to get feedback on whatever is ready at the moment.
First of all we get rid of an unused key type for public keys only. I intended it to be used when a service needs to store only public keys of its peers. However, it's not convenient to use when programming, and it's not really a new "type" – it's just the same Themis key pair, just without the private part. So, instead of inventing a new type, just reuse the existing key pair and store only the public key. Update the code to allow skipping private keys and return a more appropriate error when a private key …

Key store v2 export/import API

---

cmd/acra-keys/acra-keys.go
cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/list-keys.go
cmd/acra-keys/keys/list-keys_test.go
keystore/filesystem/server_keystore.go
keystore/keystore.go
keystore/v2/keystore/api/keyStore.go
keystore/v2/keystore/api/tests/keyStore.go
keystore/v2/keystore/filesystem/backend/api/backend.go
keystore/v2/keystore/filesystem/backend/api/tests/backend.go
keystore/v2/keystore/filesystem/backend/filesystem.go
keystore/v2/keystore/filesystem/backend/memory.go
keystore/v2/keystore/filesystem/keyStore.go
keystore/v2/keystore/keyStore.go
keystore/v2/keystore/storage_client.go
keystore/v2/keystore/storage_zone.go
keystore/v2/keystore/transport_connector.go
keystore/v2/keystore/transport_server.go
keystore/v2/keystore/transport_translator.go

Introduce a new subcommand `list` which could be used to enumerate all keys stored in the key store. This will be useful during key export to specify which keys need to be exported.
The basic usage looks like this:
```
$ acra-keys list
Key purpose                  | Client/Zone ID | Key ID
-----------------------------+----------------+-----------------------------------
client storage key           | ilammy         | client/ilammy/storage
AcraConnector transport key  | ilammy         | client/ilammy/transport/connector
AcraServer transport key     | ilammy         | client/ilammy/transport/server
AcraTranslator transport key | ilammy         | client/ilammy/transport/translator
```
Fully machine-readable output is also support with new `--json` option:
```
$ acra-keys --json list | jq
[ …
```

"acra-keys list" subcommand

---

cmd/acra-keys/acra-keys.go
cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/export.go
cmd/acra-keys/keys/keystore.go
keystore/v2/keystore/api/keyStore.go
keystore/v2/keystore/api/tests/keyStore.go
keystore/v2/keystore/filesystem/keyStore.go
keystore/v2/keystore/keyStore.go

This PR adds `export` and `import` subcommands that handle key export and import respectively.
The keys can be exported like this:
```shell
$ acra-keys list
Key purpose                  | Client/Zone ID | Key ID
-----------------------------+----------------+-----------------------------------
client storage key           | ilammy         | client/ilammy/storage
AcraConnector transport key  | ilammy         | client/ilammy/transport/connector
AcraServer transport key     | ilammy         | client/ilammy/transport/server
AcraTranslator transport key | ilammy         | client/ilammy/transport/translator
```
```shell
$ acra-keys export --key_bundle_file encrypted-keys.dat --key_bundle_secret access-keys.json --all
INFO[0000] Exported key data is encrypted and saved here: encrypted-keys.dat …
```

acra-keys export & import subcommands

---

cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/export.go
keystore/v2/keystore/api/keyStore.go
keystore/v2/keystore/api/tests/keyStore.go
keystore/v2/keystore/filesystem/export.go
keystore/v2/keystore/filesystem/keyStore.go
tests/test.py

This PR makes `acra-keys export` use a bit more safe defaults, and adds integration tests for it.
`acra-keys export` is intended to be used primarily for transferring public keys between servers running various Acra components. For this use case private keys must never leave the machine which generated them. Make sure that we do not export private keys by default. In order to export private keys (e.g., for backup) the user has to explicitly opt-in by specifying the `--private_keys` option. Without that option the private keys will not be decrypted and will not be included into the exported data set.
Specifics of the export are controlled by a new parameter: `ExportMode`. Right now it's binary (public-only or full) but later we might want to extend it and add more options, so this …

Export only public keys by default and test it

---

Makefile

AWK's `[[:space:]]` clause doesn't work on Linux, but works on MacOS.
Use space symbol instead which works well with both AWK implementations.

Fix Makefile help

---

keystore/v2/keystore/storage_zone.go

The prefix for zone storage keys is incorrect, it should be `zone`. That way the keys will be placed into correct subdirectory.

Use correct zone prefix for key store v2

---

cmd/acra-migrate-keys/acra-migrate-keys.go
cmd/acra-migrate-keys/migrate-keys/command-line.go
configs/acra-migrate-keys.yaml
keystore/filesystem/key_export.go
keystore/filesystem/server_keystore_test.go
keystore/v2/keystore/importV1_test.go

* **Common acra-migrate-keys package**
Move command-line processing into a shared `migratekeys` package which could be reused in Acra EE to provide the same command-line interface as Acra CE without a lot of copypasta.
We'll still need to use copy-paste inheritance for key store initialization and the migration process, but that's a necessary evil
because the key store instances are different. Common command-line parameters are the same, on the other hand.
* **Improve reusability of `filesystem.KeyExport`**
The main difference between Acra CE and Acra EE in key exporting is the list of keys that need to be exported and the method by which they are exported. Acra EE will need to extend and/or override these methods.
The exporting approach can be readily overridden in `ExportPublicKey()` …

Improve acra-migrate-key reusability

---

cmd/acra-addzone/acra-addzone.go
cmd/acra-authmanager/acra_authmanager.go
cmd/acra-connector/acra-connector.go
cmd/acra-keymaker/acra-keymaker.go
cmd/acra-keys/keys/command-line.go
cmd/acra-poisonrecordmaker/acra-poisonrecordmaker.go
cmd/acra-rollback/acra-rollback.go
cmd/acra-rotate/acra-rotate.go
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
configs/acra-addzone.yaml
configs/acra-authmanager.yaml
configs/acra-connector.yaml
configs/acra-keymaker.yaml
configs/acra-keys.yaml
configs/acra-poisonrecordmaker.yaml
configs/acra-rollback.yaml
configs/acra-rotate.yaml
configs/acra-server.yaml
configs/acra-translator.yaml
keystore/filesystem/server_keystore.go
tests/test.py

As discussed, let's make the behavior of tools more predictable.
All services can already detect the key store version from the actual key store data. They do not need a `--keystore` parameter at all. Remove it from almost all the tools.
However, `acra-keymaker` now requires the `--keystore` option to be specified the first time it generated the keys. That is, when then key store is initialized. It is now an error to not specify it. Requiring the version to be specified explicitly makes infrastructure configuration more predictable.
Another tool which requires explicit key store version is `acra-migrate-keys`. PR #386 takes care of it.

Require explicit key store version

---

cmd/acra-keys/keys/export.go
keystore/v2/keystore/api/keyStore.go
keystore/v2/keystore/filesystem/keyStore.go
keystore/v2/keystore/keyStore.go

Improve some of the interfaces so that they can be properly extended by Acra EE.
Avoid using Acra CE types directly in import/export interfaces of the `acra-keys` common code. Use key store interfaces instead. This enables Acra EE to use its own extended types.
Extract key description (for human-readable lists) into an overridable method so that Acra EE can add its own keys there.

Improve acra-keys extensibility in Acra EE

---

cmd/acra-keys/acra-keys.go
cmd/acra-keys/keys/acra-keys.go
cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/keystore.go

Introduce a `KeyStoreFactory` interface which encapsulates the differences between Acra CE and Acra EE implementations of `acra-keys` utility. It turns out that this is the only thing that needs to be changed. We can reuse the rest of the code.
After adapting the code to the new interface, move the business logic into the common `keys` module. Now the implementation is basically three lines:
1. Parse the command line.
2. Construct an appropriate factory.
3. Execute requested command.
The commands are the same for both Acra CE and Acra EE. New shared commands can be added to Acra CE. If there is a need for exclusive commands in Acra EE, we can add them there and reuse the common code from Acra CE for the rest of the commands.

More reusable code of acra-keys

---

cmd/acra-migrate-keys/migrate-keys/command-line.go
configs/acra-migrate-keys.yaml

The user might not like the new name of the key store to be `.acrakeys.migrated`. While it is not much of a problem for
filesystem-based key store, this might become a problem for other types, like Redis, where renaming the key store is not that straightforward.
Instead of pondering on a better name, have the user to explicitly specify it. That way the user can either choose a different name, or may keep it `.acrakeys` (but hosted in a different place).
The `--src_keys_dir` is required as well. Previously it defaulted to `.acrakeys` used by Acra by default. However, let's make it required as well for the sake of symmetry and predictability. The user already has to specify the version of the key stores and other details. It's good to make them aware of the key directory name at this moment …

Make --{src,dst}_keys_dir parameters required

---

cmd/acra-keymaker/acra-keymaker.go
keystore/filesystem/server_keystore.go

There is no definite easy way to tell whether a directory is key store v1 because it does not have any identifying features like key store v2 has: no version files, nothing. So we have used a conservative approach: if it's a directory, it's a key store v1.
However, this does not account for the case of the empty directory. Yes, it is a directory, but it's probably not a *key* directory. This may cause tools – which all use autodetection now – falsely believe that a directory *is* a key store v1. In particular, acra-keymaker will think that it's a key store v1. It will not require an explicit `--keystore` argument, and will generate v1 keys, which may not be what the user wants to achieve (or rather, what we would like the user to do).
The users might first create a directory, then pass it …

Do not treat empty directory as key store v1

---

.circleci/config.yml

Instead of having a dedicated job (with costly startup costs) for testing key store v2, verify this flavor with all databases along with key store v1. The integration tests use separate temporary directories and clean up the database after use, so we can run the tests back to back.
MySQL support code has a slightly different code path, so it might be using keys for data decryption is some weird way. TLS flavors should not be much different, but let's test them as well for consistency.

Test key store v2 with all databases

---

cmd/utils.go

This PR just adds new utility function `RegisterWithoutExiting` to system signal handler that behaves similar to `Register` but it does not call `os.Exit(0)` in the end. As we discussed, it is desirable to have better control on points of exiting from the Acra services and ideally to minimize them to the single place of exiting. `Register` is still in place, so if some of the services rely on it's `os.Exit(0)` it will not break their behavior.

Add non-exiting signal handler

---

cmd/acra-keys/acra-keys.go
cmd/acra-keys/keys/acra-keys.go
cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/keystore.go

I thought this interface is *the thing* that makes reusing code in Acra EE easier, but in fact it does not help much (and causes trouble).
I was trying to move `acra-migrate-keys` functionality into `acra-keys` multitool and ran into an architectural issue. `acra-keys` expect that key store parameters are global and there is only one set of those parameters. All subcommands of `acra-keys` acted on a single key store so that made sense.  `acra-migrate-keys` needs to specify *two* parameter sets: old and new key store. Thus, `acra-keys` in its current form cannot support the needs of `acra-migrate-keys`.
Well, it's not like `acra-keys` has been architectured beforehand in any proper way... So I'll just pretend that we're using *Agile™ Methodology* and let the code base evolve natually. …

Drop KeyStoreFactory interface

---

cmd/acra-keys/keys/acra-keys.go
cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/destroy-key.go
cmd/acra-keys/keys/export.go
cmd/acra-keys/keys/list-keys.go
cmd/acra-keys/keys/list-keys_test.go
cmd/acra-keys/keys/read-key.go

Another issue with `acra-keys` interfaces for Acra EE is that it uses `CommandLineParameters` struct directly. This means that Acra EE is forced to use Acra CE command-line parameter set and cannot add anything else there. This is problematic because Acra EE *needs* to add more key store configuration parameters.
Instead of accepting `CommandLineParameters` and accessing its fields directly, introduce a bunch of interface with accessors, delimiting options for various commands. This decouples business logic of `acra-keys` from concrete storage of parameters (and unrelated parameters). It will also allow further refactoring of `CommandLineParameters` – I'd like to split it into multiple structs later to provide a better command-line help and key store parameter CLI.
This is only …

Move acra-keys parameters into interfaces

---

cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/destroy-key.go
cmd/acra-keys/keys/export.go
cmd/acra-keys/keys/list-keys.go
cmd/acra-keys/keys/read-key.go
cmd/utils.go
configs/acra-keys.yaml

As noted by @vixentael in #396, `acra-keys` currently has incomplete configuration file template. The configuration still works, but the users won't know that they can set a particular value in the configuration file instead of passing it over and over on the command line.
The issue here is that the `DumpConfig` function used to handle the `--dump_config` flag is very tightly coupled with the global flag set (`flag.CommandLine`). However, `acra-keys` has most of its flags in flags sets of individual subcommands, not the global one.
To fix this issue, introduce a bunch of sister functions to `DumpConfig` and friends, which can accept an arbitrary list of flag sets to work with. `acra-keys` will use these functions to pass its flag sets. Other tools continue using the old functions which …

Full config for acra-keys

---

cmd/acra-addzone/acra-addzone.go
cmd/acra-authmanager/acra_authmanager.go
cmd/acra-connector/acra-connector.go
cmd/acra-keymaker/acra-keymaker.go
cmd/acra-keys/keys/export.go
cmd/acra-keys/keys/keystore.go
cmd/acra-migrate-keys/acra-migrate-keys.go
cmd/acra-poisonrecordmaker/acra-poisonrecordmaker.go
cmd/acra-rollback/acra-rollback.go
cmd/acra-rotate/acra-rotate.go
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
keystore/keystore.go
keystore/v2/keystore/crypto.go
tests/test.py

One key to rule them all,
　one key to sign them,
One key to crypt them all
　and to the env vars bind them. 
<sub>I'm sorry. I could not resist the temptation.</sub>
So... Key store v2 requires two separate master keys: one for encryption of key material and another one for signing the key store metadata. The original idea was to naturally use two separate environment variables to supply the key values. While it is easy to code, it is not really easy for the users to use. They have to generate two separate keys, store them separately, set them up separately, while conceptually they are still just one “Acra master key”.
Instead of using two separate variables for key store v2, use the same ACRA_MASTER_KEY as key store v1 uses. However, instead of expecting base64-encoded key bytes there, we …

Use single ACRA_MASTER_KEY for key store v2

---

decryptor/base/decryptionNotification.go
decryptor/mysql/column_field.go
decryptor/mysql/decryptor.go
decryptor/mysql/proxy.go
decryptor/mysql/response_proxy.go
decryptor/mysql/utils.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/pg_general_decryptor.go
decryptor/postgresql/proxy_test.go
encryptor/dbDataCoder.go
encryptor/dbDataCoder_test.go

This is a sizeable but coherent changeset improving various aspects of MySQL processing in Acra CE, with the goal of providing a better platform for Acra EE features relying on additional data processing, such as pseudonymization.
The overarching idea is that PostgreSQL proxy backend implements the `ColumnDecryptionNotifier` interface which enables subscribers to observe and modify per-column data during is processing in responses and requests. MySQL does not support this interface. Moreover, there are some other issues related to its use which are fixed up here to keep the build green.
- Integer support in MysqlDBDataCoder
First of all MySQL request parser did not support integer fields in requests. This breaks any tests for MySQL using integers because Acra simply passes such requests …

MySQL decryption notifications

---

cmd/acra-translator/server/server.go
cmd/utils.go
utils/utils.go

This PR is a technical one. It is needed for EE.
Basically it moves `DefaultWaitGroupTimeoutDuration` constant (and makes it exportable in order to reuse in other packages) to common `utils` package. Additionally it adds new `RegisterWithContext` function to signal handler utility component that actually behaves like usual `Register` but avoids `os.Exit` and allows passing global context for better controlling of background goroutine that runs it.

RegisterWithContext for signal handlers

---

acra-censor/common/matching_logic.go
acra-censor/common/matching_logic_test.go
cmd/acra-keys/keys/list-keys_test.go
cmd/acra-server/client_commands_session.go
decryptor/binary/binary_decryptor.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/packet_handler_test.go
decryptor/postgresql/pg_hex_decryptor.go
encryptor/utils_test.go
keystore/filesystem/server_keystore_test.go
keystore/filesystem/storage.go
keystore/v2/keystore/api/tests/key.go
keystore/v2/keystore/api/tests/keyRing.go
keystore/v2/keystore/api/tests/keyStore.go
keystore/v2/keystore/filesystem/export.go
keystore/v2/keystore/filesystem/keyStoreLoad.go
keystore/v2/keystore/filesystem/keyStore_test.go
keystore/v2/keystore/importV1_test.go
keystore/v2/keystore/keyRingUtils.go
keystore/v2/keystore/signature/notary_test.go
logging/log_formatters.go
logging/logging.go
network/connection_metadata.go
network/connection_wrapper.go
network/trace.go
sqlparser/dependency/sqltypes/bind_variables_test.go
sqlparser/dependency/sqltypes/plan_value.go
sqlparser/dependency/sqltypes/value.go
sqlparser/parse_test.go
zone/zone_id_matcher_test.go

* Fix `gofmt` issues (apply suggestions by `gofmt`)
* Fix misspells
* Fix golint issues (add comments to exported types and functions)
* Fix `ineffassign` issues (those are assignments to variables that are unused or rewritten afterwards)
* Fix two bugs (I guess) detected by `ineffassign`:
* In `cmd/acra-server/client_commands_session.go` the function was
returning instead of breaking `switch` and reporting error to client
* In `decryptor/mysql/response_proxy.go` we had `:=` that overrides the
scope so the new `err` was created instead of writing to already
defined one
Feel free to remove the :beetle:`bug` label if those bugs are not actually bugs and I misunderstood the code.
It turns out that CircleCI scripts are a little bit broken and `golint` check was not performed automatically …

Improve Acra Go Report scores

---

cmd/acra-keys/acra-keys.go
cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/generate.go
configs/acra-keys.yaml
keystore/filesystem/server_keystore.go
keystore/v2/keystore/poison.go
keystore/v2/keystore/webConfig.go

Add a new subcommand for key generation. This is a replacement for `acra-keymaker` and other tools like `acra-addzone`.
The first step is to generate a master key:
```
acra-keys generate --master_key_path=master.key --keystore=v2
```
The `--keystore` option is required since the format of master keys is different for keystore versions.
The resulting master key is placed into the specified file. It needs to be set in the environment:
```
ACRA_MASTER_KEY=$(cat master.key | base64)
```
After you have a master key, generate the initial keystore:
```
acra-keys generate --keystore=v2 --client_id=ACME
```
The `--keystore` option is required here as well since we need to know which format to use. When the keystore is already initialized, this option is not necessary as `acra-keys` can see the …

Generate keys with "acra-keys generate"

---

keystore/v2/keystore/api/tests/keyStore.go

[Go 1.15 has changed serialization of "SET OF" elements in ASN.1][1] to be sorted. This means that now the serialized form of exported key rings does not preserve the order in which they have been given to the `Export()` method. Therefore, we cannot depend on `Import()` to return their names after import in the same order. Replace the slice comparison with unordered comparison.
Some tests also depended on keys being exported and imported sequentially in the given order. This is no longer the case with Go 1.15 so tweak the tests to avoid such dependency.
[1]: https://golang.org/doc/go1.15#encoding/asn1
This issue has been found by @iamnotacake in #410 and is actual only for Go 1.15+. ~~This PR should wait until that one is merged, and bump the Go version to 1.15 for CircleCI to run the …

Fix Go 1.15 regression in keystore tests

---

cmd/acra-keys/keys/command-line.go
cmd/acra-keys/keys/destroy-key.go
cmd/acra-keys/keys/read-key.go
configs/acra-keys.yaml
tests/test.py
tests/utils.py

Change the CLI of `acra-keys read` and `acra-keys destroy` to match other subcommands (like `export` and `list`).
Now instead of
```
acra-keys read --client_id Alice storage-public
```
you should write
```
acra-keys read --public client/Alice/storage
```
where the last part is the "key ID" which you can see in `acra-keys list` output.
```
Key purpose                  | Client/Zone ID | Key ID
-----------------------------+----------------+----------------------------------
client storage key           | Alice          | client/Alice/storage
AcraConnector transport key  | Alice          | client/Alice/transport/connector
AcraServer transport key     | Alice          | client/Alice/transport/server
AcraTranslator transport key | Alice          | client/Alice/transport/translator
```
This …

Unify key ID paths in "acra-keys"

---

cmd/acra-translator/grpc_api/api_test.go
cmd/acra-translator/http_api/mock_keystorage.go
decryptor/base/utils.go
decryptor/mysql/decryptor.go
decryptor/mysql/decryptor_test.go
decryptor/postgresql/pg_general_decryptor.go
keystore/filesystem/server_keystore.go
keystore/keystore.go
keystore/v2/keystore/poison.go
zone/zone_id_matcher_test.go

Previously we have implemented usage of historical decryption keys for AcraStructs with user data. This PR teaches Acra to use historical keys for poison records as well. While it is currently not possible to rotate poison record keys, it might become possible in the future and with this PR we will be ready for that. With this change the `DecryptAcrastruct` function is no longer used directly in any code other than tests (which test that AcraStructs decrypt with a specific key). Now all code is using `DecryptRotatedAcrastruct` with multiple keys.
A new keystore method `GetPoisonPrivateKeys` returns all private keys used for poison records. It is similar to `GetPrivateKeys` used to retrieve private keys for user data decryption. Just like `GetPoisonKeyPair`, it will implicitly generate a …

Use historical poison record keys

---

cmd/acra-server/acra-server.go
cmd/acra-server/common/client_commands_session.go
cmd/acra-server/common/client_session.go
cmd/acra-server/common/config.go
cmd/acra-server/common/listener.go
cmd/acra-server/common/prometheus.go
cmd/utils.go

This PR improves code reuse in AcraServer by moving shared code into a separate package which can be imported from Acra EE. (It is not possible to import packages providing binaries.)
The shared code now lives in the `common` module, similar to AcraTranslator. It has been cleaned up and refactored a bit to allow Acra EE to inject its own configuration where necessary.
Here we make no effort to split the ginormous `main` function into more reusable bits. This is an adventure for another day.
There should be no user-visible changes due to this refactoring. More technical details are available in commit messages.

Move AcraServer common files into "common" package

---

cmd/acra-server/common/client_commands_session.go
cmd/acra-server/common/client_session.go
cmd/acra-server/common/listener.go
decryptor/base/proxy.go
decryptor/mysql/proxy.go
decryptor/mysql/proxy_test.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/proxy.go
decryptor/postgresql/proxy_test.go

This is a preparatory refactoring for prepared statement implementation.
Prepared statements are inherently associated with a *session* – a connection from the client to the database which is effectively proxied by AcraServer. There is a concept of session in AcraServer's command code (`cmd/acra-server` module), but the decryption proxy code is oblivious to that. It works with just a pair of connections: the one from the client to the AcraServer, and other one from AcraServer to the database.
Here we introduce a more specific concept of client session, defined by the `ClientSession` interface which the proxy code is taught to use. In order to make that happen we need to refactor quite a bunch of code so there are a lot of things happening in this PR.
The recommended way to review is by …

Extract ClientSession interface

---

cmd/acra-server/acra-server.go
cmd/acra-server/common/listener.go

This PR introduces refactoring on main component level (`SServer`) of AcraServer service.
I used approach, described in T1661 and already implemented in https://github.com/cossacklabs/acra/pull/414 for AcraTranslator. Just short reminder: we need better control of shutdown process because it is very important for EE version in context of audit logging (where we need to finish execution of service with special service log messages). So here on main component level I added synchronization of spawned goroutines (with a help of `waitGroup` mechanism) and signalling of shutdown invocation with a help of `parentContext` (passed to `SServer` from main function of AcraServer).
For testing I used two versions of AcraServer (CE and EE), according to the procedures described in …

AcraServer refactoring for better shutdown control

---

tests/utils.py

Instead of using hardcoded string 'python' as Python command,
read the path of interpreter we're currently using from `sys.executable`.
This is usable when there's no `python` in $PATH or it points to `python2` while we're using `python3`.
Also, it's more correct way of running Python scripts from Python scripts as [PEP-0394](https://www.python.org/dev/peps/pep-0394/#for-python-script-publishers) says.

Fix Python executable path in scripts

---

cmd/acra-server/common/client_session.go
decryptor/base/proxy.go
decryptor/mysql/proxy_test.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/prepared_statements.go
decryptor/postgresql/prepared_statements_test.go
decryptor/postgresql/proxy_test.go

In order to handle prepared statements we need to keep track of them. This is what registries are for.
Implement a couple of simple objects to keep track of name → entity mappings. Both prepared statements and cursors are identified by name. (In PostgreSQL they may be anonymous as well, with empty names.) There are simple accessors to their core properties: the query which is prepared, and the statement which is iterated by a cursor.
These interfaces are pretty much preliminary as I'm not sure what we'll need for the implementation. They may also be unnecessarily extensible. For one, we might not actually need PostgreSQL and MySQL specific registries. For now, keep it like that in case we'd need to add something PostgreSQL-specific. However, if that won't happen then all of this is likely …

Prepared statement and cursor registries

---

decryptor/base/observers.go
encryptor/queryDataEncryptor.go

Since prepared statements are going to work closely with the `QueryDataEncryptor`, I've reviewed this interface and its uses. Turned out, it's very similar to `DecryptionSubscriber` which has recently acquired and `ID()` method, allowing to identify which of the subscribers have failed decrypting the query. The encryption code path has the same logic but no way to identify the culprit. Granted, Acra CE has only one `QueryDataEncryptor`, but Acra EE has several and it would be useful there.
Add an `ID()` method to `QueryDataEncryptor` and refactor the `ArrayQueryObserverableManager` – the entity providing multi-observer capabilities – to use this new method for improved error logging.
While we're here, do some other minor changes.
- Do not log the query again in …

IDs for QueryDataEncryptors

---

cmd/acra-server/common/client_session.go
decryptor/base/proxy.go
decryptor/mysql/proxy_test.go
decryptor/postgresql/packet_handler.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/protocol.go
decryptor/postgresql/proxy_test.go

Introduce a separate object to take care of PostgreSQL protocol packets. With extended protocol we will need to track both requests and responses before we are able to process a query, so we need a place to store this information temporarily.
The protocol state is fundamentally associated with the session so it makes sense to keep one there. However, we need to keep it opaque as MySQL and PostgreSQL protocols are very different. For now, let's use just `interface{}` as a placeholder. Maybe later we will be able to extract some more specific interface out of the implementations.
`PgProtocolState` keeps user query in memory until the database issues a response. The query text is sensitive information, especially when transparent encryption is in use. We should remove it from memory as soon …

PgProtocolState handler

---

decryptor/postgresql/packet_handler.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/protocol.go
decryptor/postgresql/utils.go
utils/utils.go

Add (or update) parsers for new extended protocol packets that we're interested in:
- **Parse** and **ParseComplete** which prepare statements for execution
- **Bind** and **BindComplete** which carry parameters for prepared statements
- **Execute** which initiate prepared statement execution
This gives us all the context information we will need for later processing of extended queries. Use it to maintain prepared statement and cursor registries.
For now, we only observe the protocol flow between the client and the database and don't do much extra about it, only logging when we catch this or that packet. The current integration test suite already has some tests which use the extended protocol: `TestPgPlaceholders`, `CensorBlacklistTest`, `CensorWhitelistTest`, …

Observe extended query protocol

---

decryptor/base/observers.go
decryptor/postgresql/packet_handler.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/utils.go
encryptor/queryDataEncryptor.go
tests/test.py

This PR adds transparent encryption of prepared statement parameters for PostgreSQL binary protocol. That is, when a **libpq** driver uses prepared statements, AcraServer will be encrypting not only the values given directly in the prepared SQL query text, but also the parameters passed during prepared statement execution.
Many drivers use the prepared statement protocol—technically called *extended query protocol*—for all queries, not just prepared ones. The extended protocol provides some *extended* flexibility. In this case the **Bind** messages are empty and don't carry any parameters. However, if the parameters *are* used, typically to implement actual prepared statements, AcraServer did not process them. Now it does.
Note that this **does not** add support for *textual* prepared …

Transparent encryption of prepared statement parameters

---

encryptor/queryDataEncryptor.go
tests/test.py

It turns out that clients don't really use text formats for data types which are interesting to Acra CE's transparent encryption. It works only with byte arrays which are typically using binary format.
Text format may be occasionally used for types interesting to Acra EE: currently integers and floats. However, Acra EE's encryptors *expect* such data in text format in the first place.
Therefore, for text format of parameters we need to pass them as is. It's the binary format which requires more attention. If the parameter is integer – it still must be encoded as text for the encryptor, even if the parameter is binary.  We'll need to know what type the parameter has and then possibly decode and reencode it after encryption. Right now that's not possible. We continue passing binary data as …

Basic support of text format for parameters

---

cmd/acra-server/acra-server.go
network/tls_authentication.go
network/tls_wrapper.go
network/tls_wrapper_test.go

To encapsulate calls order of identifier extractor and convertor into one component, I added TLSClientIDExtractor which aggregate and encapsulate that logic and simplify re-usage in parts which don't need to wrap connections to TLS, only extract info from already established connection and TLS state (acra-translator), plus it will simplify code re-usage in acra-ee

Merge identifier extractor and convertor

---

cmd/acra-connector/acra-connector.go
cmd/acra-server/acra-server.go
network/cert_verifier.go
network/tls_wrapper.go

Create a function `RegisterCertVerifierArgs()` which will now be responsible for handling OCSP- and CRL-related command line flags.
In acra-server and acra-connector, call it instead of describing all these flags (which are mostly duplicated).
Then, call one of
* `NewCertVerifierFromArgs()`
* `NewClientCertVerifierFromArgs()`
* `NewDatabaseCertVerifierFromArgs()`
which will use values generated by `RegisterCertVerifierArgs()` and create the CertVerifier under the hood.
All these changes will allow editing/adding/removing flags much easier since they will be in one place.
Also, adding cert verification functionality to different binaries in `cmd/` will require writing less code:
* one call to register flags,
* another one to get the verifier we can use in TLS wrapper.

Handle certificate validation flags in single place

---

network/cert_verifier.go
network/crl.go
network/ocsp.go
network/tls_authentication.go
tests/test.py

When we run acra-ce tests with binaries from acra-ee, working directory used from acra-ee environment, where not exists `tests/ssl/*` folders and files. So to avoid errors, we should rely on abs paths in acra-ce tests and calculate them relative to files in acra-ce.
p.s. also fixed some naming issues to pass linter's checks

Use absolute path for files in tests

---

network/crl.go
network/crl_test.go
network/ocsp.go
network/ocsp_test.go

Additional unit tests for better coverage of OCSP client & verifier behavior.
Small bugfix where OCSPClient did not check whether response was related to asked certificate, now it will return error if mismatched.

Additional unit tests for certificate verifier

---

CHANGELOG.md

Fix link in CHANGELOG to Github release page.

Fix link in CHANGELOG to Github release page

---

docker/docker-compose.mysql-nossl-server-ssl-connector_zonemode.yml
docker/docker-compose.pgsql-ssl-server-ssl-connector_zonemode.yml

has run all docker-compose files and tried to connect to be sure that acra-server/acra-connector up and accept connections, and found 2 files with missing parameter that fail hinders acra-server startup.
- [+] [Example projects and code samples] are up-to-date (in case of API changes) 
[Example projects and code samples]: …

add missing parameter --client_id according to same file without zone mode

---

.circleci/integration.sh
CHANGELOG_DEV.md
acra-censor/common/logging_logic.go
acra-censor/common/logging_logic_test.go
docker/ci-py-go-themis.dockerfile

* Added `file.Sync` calls in tests before reading files to be sure that all data dumped
* A bit refactored `QueryWriter`'s time constants and changed them to variables. Now we can change them in our tests to reduce time of waiting (decreased from 6s to ~1s)
* Removed some cache deletion in our scripts. I checked that golang take care of invalidation result binaries with different golang versions. It detects that binary has been built by another compiler and rebuild it if need. 
* Added downloading golang sources of dependencies to our base docker image to reduce time of tests on CircleCi (and local too)
[Acra documentation]: …

[T2316] fix flaky acra-censor's tests

---

examples/python/example_with_zone.py
examples/python/extended_example_with_zone.py

Removed `acra-connector` related variable from python examples

Remove connector variable from python examples

---

acra-censor/acra-censor_test.go
acra-censor/common/file_log_storage.go
acra-censor/common/logging_logic.go
acra-censor/common/logging_logic_test.go
cmd/acra-translator/http_api/service.go
cmd/acra-translator/http_api/service_test.go
network/connection_wrapper_test.go

* added help function that wait until all sent queries processed in background goroutine of querywriter and then validate results 
in tests. it helps to not depend on golang's scheduler and provided time for background goroutine
* updated censor's test with unparsed queries, where changed hardcoded file path to temporary file. It allows to run a lot of 
tests at once
* configured HTTP client to not re-use connections in AT tests with secure session that also make tests flaky. we decided to ignore this issue due to future removing acra-connector and secure session, and don't spend time on it
* when tried to fix SS issue, also extended connection wrapper tests, to run them with TCP connections too, not only unix sockets synchronized and buffered by OS. OS may divide big packets differently …

Third approach to fix failure censor's test

---

CHANGELOG_DEV.md
sqlparser/ast.go
sqlparser/ast_methods.go
sqlparser/ast_test.go
sqlparser/parse_test.go
tests/test.py

Due to using sqlparser that targeted to MySQL, it didn't use to support postgresql's type castings, especially `null::text`.
Previously we extended SQLVal to support `::<type>` type casts, to avoid a lot of refactorings and re-use existing code that depends on SQLVal (for example our transparent encryption). But it's simplest way to support such type casts. Harder is to refactor `sql.y` and used SQL's grammar, and propagate casts to all kinds of lexical rules related to SQL values (`select expr`, `functions`, etc). 
But Acra works with simple SQL value literals and don't support complicated SQL values like functions or `(select 1)::text`, so for now we don't need to do it and can leave it for later (probably we will switch to another parser earlier than meet real case where it need:)
So …

Handle null::text casts in postgresql dialect, fix panics

---

CHANGELOG_DEV.md
acra-censor/common/logging_logic.go

Here removed extra statement with default that avoid expected blocking execution and work as infinite loop.
There is no tests because I don't know how to test removing this statement without overengineering like add more logs, subscribe in tests with new handler and check that logs weren't generated. But this log entry we don't need even with debug level and will produce redundant messages...
So imho, we can just remove this statement and believe that it works better. But maybe someone can suggest some way to test it, I will add it.
- [-] Change is covered by automated tests …

Remove infinite empty loop

---

CHANGELOG_DEV.md
network/crl.go
network/crl_test.go

CRL contains revoked certificates as a simple list, which means validating certificates is O(N).
Most certificates will be valid which means validator would have to search through the whole list each time.
This improvement is about making verification O(1) operations thanks to `map` being used instead of plain array.

CRL validation improvements

---

CHANGELOG_DEV.md
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
configs/acra-server.yaml
configs/acra-translator.yaml
logging/event_codes.go
poison/callbacks.go
tests/test.py

* turned off poison record detection for server and translator
* added integration tests for translator with poison record detection (were only for server)
* added logging about turning on poison record detection at startup
* fixed failure of prometheus tests due to port collision (works on CI because we re-define ports for acra-server)
* changed a bit timeouts to use lower sleeps but same total timeout
* removed tests for whole cell mode with poison records because this option ignored far ago
* updated docs - https://github.com/cossacklabs/product-docs/pull/230
- [+] …

Turn off poison detection by default for AS/AT

---

CHANGELOG_DEV.md
keystore/filesystem/server_keystore.go
keystore/filesystem/server_keystore_test.go
tests/test.py

Just added MkdirAll to KeyStore.WriteKeyFile() to create dir preliminarily.

Fixed acra-keymaker  sym key generation into uncreated dir

---

examples/python/encryptor_config_with_zone.yaml
examples/python/extended_encryptor_config_with_zone.yaml
examples/python/extended_encryptor_config_without_zone.yaml

Adding extended pyhton encryptor configs. Need to support two different kind of encryptor configs with default envelope. Because different examples should use different configs.

Add python example extended configs

---

CHANGELOG_DEV.md
decryptor/base/proxy.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go
network/crl.go
network/crl_test.go
network/errors.go
network/ocsp.go

Extended our error handling in cases when we try to convert raw connection to TLS connection with suggestions that should help to debug or fix issues.
These events occurs at start of communication with databases and don't repeat. So it is not frequent events in normal operation flow. So IMHO, we can log it with `INFO` level instead of `DEBUG`
- [-] Change is covered by automated tests
- [+] [Example projects and code samples] are up-to-date (in case of API …

Add suggestions for problems with tls connections

---

CHANGELOG.md
CHANGELOG_DEV.md
acrablock/dataEncryptor.go
acrablock/dataEncryptor_test.go
cmd/acra-keys/keys/read-key.go
cmd/acra-translator/grpc_api/service.go
cmd/acra-translator/grpc_api/service_test.go
cmd/acra-translator/http_api/service_test.go
crypto/acrablock.go
crypto/encryptor_test.go
crypto/matcher_test.go
crypto/reencryptor_test.go
keystore/filesystem/server_keystore.go
poison/poison.go
pseudonymization/storage/storageTokenEncryptor.go
tests/test.py

* Use the optimized new method for fetching symmetric encryption key instead of set of keys
* Update tests that verify that new method used
* adapt integration test script for python3.6 that used in Centos 7/8. Remove `default` keyword for namedtuple that introduced in python3.7 and `--directory` parameter for `http.server` and specify the working directory for fork.
- [+] [Example projects and code samples] are …

use Get*SymmetricKey API instead of Get*SymmetricKeys

---

CHANGELOG_DEV.md
acra-censor/acra-censor_test.go
acra-censor/common/logging_logic.go
acra-censor/common/logging_logic_test.go
acra-censor/handlers/querycapture_handler.go

This removes unnecessary field `IsForbidden` from `QueryInfo`, which was used only in a couple of tests. This could potentially break the user API, so it is documented [here](https://github.com/cossacklabs/product-docs/pull/238).
with new changes.

Acra-censor: remove is forbidden

---

Makefile

Escape sequences are not interpreted in `echo` if `-e` is not passed. Because of that, `make help` looked like:
<details>
<summary>Before</summary>
```
$ make help
\033[1mTargets:\033[0m
help            Show this help
build_protobuf  use this target only when it is really needed, not for usual builds
build           Build the application in the subdirectory (default)
install         Build the application and install to the system GOPATH
test            Test the application
test_python     Run extra python test
clean           Remove build artifacts
keys            Generate keys
docker-build    Docker : build the image locally
docker-build-ci Docker : build CI-related images
docker-push     Docker : tag and push image to remote registry
docker-push-ci  Docker : tag and push CI-related …
```

Fix echoing with escape sequences

---

keystore/filesystem/key_names.go
keystore/filesystem/server_keystore.go
keystore/filesystem/server_keystore_test.go
keystore/keystore.go

Removing `TokenKeystore` interface and all related methods.

Remove legacy TokenKeystore

---

.gitignore
CHANGELOG_DEV.md
cmd/acra-keymaker/acra-keymaker.go
cmd/acra-keys/keys/generate.go
cmd/acra-poisonrecordmaker/acra-poisonrecordmaker.go
cmd/acra-translator/grpc_api/api_test.go
cmd/acra-translator/grpc_api/service_test.go
crypto/poison_detector.go
keystore/filesystem/server_keystore.go
keystore/filesystem/server_keystore_test.go
keystore/keystore.go
keystore/mocks/KeyStore.go
keystore/mocks/ServerKeyStore.go
keystore/v2/keystore/importV1_test.go
keystore/v2/keystore/poison.go
keystore/v2/keystore/poison_test.go
poison/poison.go
sqlparser/sql.go

Right now every call to the `GetPoison*` creates keys, if they don't exist. These results in a superfluous side effect, unexpected behaviour and delays in decryption (because we try to check records with fresh keys, which obviously do nothing useful).
Change this, by:
- Introducing new interface, which is responsible for poison key generation
- Removing creation of keys in `Get` methods
Also, keep this behaviour for poisonrecordmaker, but do this explicitly.
with new changes: [here](https://github.com/cossacklabs/product-docs/pull/239).
[documentation repository]: …

Don't generate poison keys during the query

---

CHANGELOG.md
keystore/filesystem/key_export.go
keystore/filesystem/server_keystore.go
tests/test.py

When AcraServer/AcraTranslator starts and loads all the keys into cache (if the option is enabled), ignore old keys related to AcraConnector.
Add new key kind "legacy" and ignore this key if found inside keystore.

Ignore legacy keys when caching keys on startup

---

decryptor/postgresql/type_conversion.go
decryptor/postgresql/type_conversion_test.go

Found that `bytes` `data_type` not handled properly for postgresql
- [+] [Example projects and code samples] are up-to-date (in case of API changes) 

Convert 'bytes' data_type to BYTEA oid for postgresql

---

decryptor/mysql/prepared_statements.go
decryptor/mysql/prepared_statements_test.go
decryptor/mysql/response_proxy.go

During conversation with @Lagovas about [#517 ](https://github.com/cossacklabs/acra/pull/517). We faced that we didnt change data_types for intermediate params/columns ColumnDefinition that are following after COM_STMT_PREPARE_OK packet. It wasnt noticed at previous PR because all driver ignore it and use only last metadata field from STMT_EXECUTE packet. But we do have to change it because some ORM might use these intermediate packet to make some cachin on its own side. 

Update params/columns data_types  for prepare packet

---

CHANGELOG_DEV.md
decryptor/base/encoder.go
decryptor/base/proxy.go
decryptor/postgresql/data_encoder.go
decryptor/postgresql/data_encoder_test.go
decryptor/postgresql/pg_decryptor.go
encryptor/config/common/encryptedTypes.go
encryptor/config/common/encryptedTypes_test.go
encryptor/config/encryptionSettings.go
encryptor/config/schemaStore_test.go
encryptor/config/tableSchema.go
encryptor/dataEncryptor_test.go
tests/encryptor_configs/transparent_type_aware_decryption.yaml
tests/test.py

One of the last PRs added support for type awareness. That allows defining types on values, which would be decrypted and returned from Acra, like string or int. It also added default values field in configs, which allows to specify which value to return, if some error (possibly decryption error) occurs.
This PR adds ability to chose, which action should be performed on (decryption) failure: either to return client specific error, like acra censor already can, or return default value. 
Default action, if type awareness is enabled, is "error". The user can specify the "default" case together with a default value.
[Acra …

Add db-specific error

---

examples/python/common.py
examples/python/data.json
examples/python/extended_encryptor_config_with_zone.yaml
examples/python/extended_encryptor_config_without_zone.yaml
examples/python/extended_example_with_zone.py
examples/python/extended_example_without_zone.py

As part of acra-engineering demo Type Awareness feature we need to extend python examples to support it. 
Since python examples from acra are used inside acra-engendering demo, this PR is part of acra-eng demo modification. 
This PR contains little extends of encryptor configs with new `data_type` fields. Important part is adding one more schema inside py files. These are needed to construct table inside DB(with raw fields) and another for making queries (with defined type)

Update python extended example

---

CHANGELOG_DEV.md
cmd/acra-server/common/listener.go
decryptor/postgresql/pg_decryptor.go
tests/test.py

Right now, if some clients receive `SSL deny` from the server, they can try to start plain connection by sending plain `Startup message`. The last one would then be served not as a startup, but as a general one, which will hang a connection.
This PR fixes this by reloading client thread after `ssl deny` to expect startup message again.
There are a couple of `TODO`s, which I hope you will help me to resolve.

Allow plain connection after ssl deny

---

CHANGELOG_DEV.md
Makefile

This command installs all tools required to successfully run the `go generate` command.
It's needed for the acra-ee deployment and testing.

Add `make install_dev_deps`

---

examples/python/encryptor_config_with_zone.yaml
examples/python/encryptor_config_without_zone.yaml
examples/python/example_with_zone.py

Actualizing python examples. 
- Updated `encryptor_config_*` with explicit table declaration to run with transparent encryption and be able to show type awareness functionality
- Deleted `zone_id` field to be able to match zone from the query but not from the table.
- Updated `write_data` function with explicit zone_id literal - deleted `cast` operator as it is not supported by Acra sql parser now.  

Update python examples

---

CHANGELOG_DEV.md
decryptor/mysql/response_proxy.go
tests/encryptor_configs/transparent_type_aware_decryption.yaml
tests/test.py

This PR implements flushing of db-packets till the end of response after the encoding error. This is done to clear the connection so it can be reused for other queries (like `rollback` for example).
This also adds a couple of tests that show the correctness of the execution. I also wanted to add test with query which produces mysql error after a couple of data packets, so we can check that acra throws "encoding error" earlier and eats the mysql one. But I just couldn't craft such query ._.
Mysql returns `null` in almost every error case (division by zero, unable to allocate `REPEAT('A', 1TB)`, etc). In cases where I could trigger a runtime error it is not possible to use acra, because query is complex. Maybe you can come up with an idea?  
[coding guidelines]: …

Don't abort connection in mysql after encoding error

---

CHANGELOG_DEV.md
decryptor/postgresql/pg_decryptor.go
tests/test.py

This PR implement skipping postgres packets from database after encoding error, almost in the same way as the previous PR does for mysql. It also adds a bunch of tests for different cases:
- Simple queries
- Extended queries (and prepared statements, that are basically the same under the hood).
- Batched extended queries (when database sends `n` packets and waits for the next request)
The only issue with postgres is that a state of transaction is stored at database side, and changes in case of some errors (even parsing ones). When the state is changed, `commit` is basically `rollback`:
```
test=# begin;
BEGIN
test=*# select 1/0;
ERROR:  division by zero
test=!# commit;
ROLLBACK
```
But our error will not trigger that:
```
test=# begin;
BEGIN
test=*# select value_bytes from testtype; …
```

Do not abort connection after encoding error in postgresql

---

CHANGELOG_DEV.md
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/pg_decryptor_test.go

This PR solves double registration of prepared statements. They are registered twice: after `Parse` and `ParseComplete`, but because of a race condition, the pending statement can be replaced by another. Then, this triggers registration of a `nil` value as a statement.
To solve the problem, this PR removes the second registration.
There is one issue though: prepared statements are never cleaned, even ones that contain errors. This requires a large redesigning of the whole packet processing protocol. So, for now, we have a small _memory leakage_ in a connection. But on practice this should not be an issue.
[Acra documentation]: …

Fix multiple prepared stmt registraion

---

CHANGELOG_DEV.md
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/protocol.go
tests/test.py

This PR solves interference problem of placeholders. They are saved in the connection, but were never removed, only replaced. That means, they could affect other queries on the same connection.
Solve this, by removing the placeholders at the end of the query: when `ReadyForQuery` arrives. 
I didn't write a new test for this, because 1) it already existed as a part of another test and 2) it's really hard to reproduce.

Remove placeholders from connection when done

---

CHANGELOG_DEV.md
encryptor/queryDataEncryptor.go
tests/test.py

This small PR adds support of mysql _binary charset introducer, which is used at least by java frontend. I would like to add other charsets, but they are not supported by the parser yet. So, if there is no need, I wouldn't do that.

Handle binary char set introducer

---

tests/test.py

As @Lagovas said [here](https://github.com/cossacklabs/acra/pull/541#discussion_r878134893), there is a common pattern of creating an executors with custom arguments. This PR factors this out into a mixin class with already established 
Decided to do it as a separate PR, to make PRs atomic in terms of changes and to make review easier.

Refactor test executors

---

CHANGELOG_DEV.md
decryptor/postgresql/packet_handler.go
decryptor/postgresql/pg_decryptor.go
tests/requirements.txt
tests/test.py

This PR fixes substitution of OID in packets. Before, it substituted them in the data messages, which are returned by select. But there is another place where they can arrive - in parse packets. We missed it, because they are optional and most frontends do not specify them.
To test it, I've added a new dependency to our python tests - psycopg3. The first stable version was released on [2021-10-13](https://www.psycopg.org/articles/2021/10/13/psycopg-30-released/), but I think we can start to use it because of its support of various features. For example in this case, this frontend sets the type of parameters in the parse packets. Also it helped to discover bug with encoding of i32, so in some cases tests could fall. I will fix it as soon as possible.
[coding guidelines]: …

Substitute oid in parse

---

CHANGELOG_DEV.md
crypto/envelope_detector.go
decryptor/mysql/response_proxy.go
tests/test.py

On decryption our envelope_detector returned `[]byte{}` on `nil` values instead leaving `nil`. MySQL encoded differently empty strings and NULL values. [NULL values should](https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-ProtocolText::ResultsetRow) have 0xfb value. So on Acra side when it receive null value as 0xfb then it changed to empty array and encode it as LengthEncoded [String](https://dev.mysql.com/doc/internals/en/string.html#packet-Protocol::LengthEncodedString) or Integer that are incorrect.
So in this PR removed processing null data in crypto envelope. If it will be empty array, it will be returned as empty array too.
- [+] Public API has proper documentation in the …

[T2580] Fix handling null values in mysql

---

Makefile
docker/ci-py-go-themis.dockerfile

Makefile contains installing the latest mockery version which requires go 1.18. Acra should support at least three latest versions. Just downgrade the mockery version to be able to build Acra with a version lower than 1.18.

Fix mockery version downgrade

---

tests/test.py

Ukrainization is good, but only on the battlefield and during destruction of the rashists :)
I've configured my code editor to highlight the cyrillic symbols, so it shouldn't happen anymore...

Remove cyrillic symbols from tests

---

cmd/acra-addzone/acra-addzone.go
cmd/acra-backup/acra-backup.go
cmd/acra-keys/keys/generate.go
cmd/acra-keys/keys/keystore.go
cmd/acra-poisonrecordmaker/acra-poisonrecordmaker.go
cmd/acra-rollback/acra-rollback.go
cmd/acra-rotate/acra-rotate.go
cmd/acra-translator/acra-translator.go
configs/acra-addzone.yaml
configs/acra-backup.yaml
configs/acra-keys.yaml
configs/acra-poisonrecordmaker.yaml
configs/acra-rollback.yaml
configs/acra-rotate.yaml
configs/acra-translator.yaml
keystore/keyloader/kms/kms_cli.go
tests/test.py

Updated Acra tools with latest KMS CLI flags to support MasterKey loading.

Update Acra tools with kms cli

---

CHANGELOG_DEV.md
go.mod
go.sum

Runs `go mod tidy -go=1.17`. This PR updates the `go` version `in go.mod` to 1.17 to match the minimum supported Go version in CircleCI and Dockerfiles.
Reference: https://github.com/cossacklabs/acra/pull/558

build: update `go` directive in `go.mod` to 1.17

---

CHANGELOG_DEV.md
cmd/acra-keys/keys/generate_test.go
cmd/acra-keys/keys/read-keys_redis_test.go
cmd/acra-keys/keys/read-keys_test.go
cmd/acra-keys/keys/read-keys_tls_redis_test.go
keystore/keyloader/kms/kms_loader_test.go
keystore/keystore_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
```
with new …

test: use `T.Setenv` to set env vars in tests

---

CHANGELOG_DEV.md
cmd/acra-keys/keys/generate_test.go
cmd/acra-keys/keys/read-keys_redis_test.go
cmd/acra-keys/keys/read-keys_test.go
cmd/acra-keys/keys/read-keys_tls_redis_test.go
keystore/filesystem/server_keystore_test.go
keystore/v2/keystore/filesystem/backend/filesystem_test.go
keystore/v2/keystore/filesystem/keyRing_test.go
keystore/v2/keystore/filesystem/keyStore_test.go
keystore/v2/keystore/filesystem/key_test.go
keystore/v2/keystore/importV1_test.go
keystore/v2/keystore/poison_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
``` …

test: use `T.TempDir` to create temporary test directory

---

cmd/acra-keys/keys/destroy-key.go
poison/callbacks.go
sqlparser/ast.go
sqlparser/parse_next_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

delete minor unreachable code

---

go.mod
keystore/kms/aws/key_manager.go
keystore/kms/base/key_making_wrapper.go

During playground actualization, faced a problem running Acra after KMS keys creating by `acra-keymaker`
```
acra-keymaker-ee_server-user1_1  | 2022-08-30T22:20:36.921200901Z time="2022-08-30T22:20:36Z" level=info msg="Initialized KMS AWS KeyManager"
acra-keymaker-ee_server-user1_1  | 2022-08-30T22:20:36.921550967Z time="2022-08-30T22:20:36Z" level=info msg="Initialized KMS AWS KeyManager"
acra-keymaker-ee_server-user1_1  | 2022-08-30T22:20:37.091789707Z time="2022-08-30T22:20:37Z" level=info msg="KMS key created" key-name=acra_fca9e56609eea6521d95f50dca9ebe45505642727ae179050ee4951f2327575535cd41226988c46790a0ba2e0b0b72542166e0f1561348ac25dc8b97803a52df keyID="arn:aws:kms:eu-west-1:533306693851:key/e6483ab7-7571-4572-8518-2ff1dc19cee4"
acra-keymaker-ee_server-user1_1  | …
```

Add KMS CreateKey waiter

---

CHANGELOG_DEV.md
decryptor/postgresql/packet_handler.go
decryptor/postgresql/packet_handler_test.go
decryptor/postgresql/pending_packets.go
decryptor/postgresql/pending_packets_test.go
decryptor/postgresql/pg_decryptor.go
decryptor/postgresql/protocol.go
tests/test.py

What was the problem? DB drivers can send set of packets in one TCP packet. And usually, they are related to each other and look like Parse + Bind + Describe + Execute + Sync. Driver registers query in Parse, then binds data, then asks to describe types, executes query and commit state. Acra registers PreparedStatement on ParseComplete packet that DB responds to driver after validation and acceptance. Bind packet relates to Parse packet because it should specify statement name for which it sends values.
In this flow acra do next: remembers Parse packet and save it as `pendingParse`. Then handle Bind packet, loads finds `pendignParse` and link them together. 
Previously we expected that one set of packets in TCP packet contains only one packet with a query like SimpleQuery or Parse packet. …

Process sequence of pending packets

---

CHANGELOG_DEV.md
decryptor/postgresql/utils.go
decryptor/postgresql/utils_test.go
tests/test.py

Previously we missed the logic of handling NULL values which should be encoded differently than empty strings. We encoded them as empty strings instead of placing `-1` value according to [wire protocol](https://www.postgresql.org/docs/current/protocol-message-formats.html)
This should fix #591.
- [+] [Example projects and code samples] are up-to-date (in case of API changes) 
[coding guidelines]: …

Fix handling null values for postgresql in binary mode

---

encryptor/queryDataEncryptor.go
encryptor/searchable_query_filter.go
encryptor/utils.go
encryptor/utils_test.go
tests/test.py

Currently, Acra expects that columns in `SELECT` statement haven't been aliased if FROM has a non-aliased table or they should have proper alias. But databases allow specific alias for table but use columns without an alias.
So if the query contains Columns without aliases and the table is aliased, Acra should consider this table as default. Added checking for containing aliases in tables expressions and switch between extracting tables functions depending on queries.

Fixed bug with matching default table with alias

---

tests/requirements.txt

Downgrade `boto3` version to `1.23.10` to match with Centos7/8 available versions

Downgrade boto3 version to 1.23.10

---

tests/requirements.txt
tests/test.py

Here are several updates to simplify running tests on centos 7/8 which uses python 3.6.8. Replaces `shutil` to simplified version and used pre-compiled psycopg2 due to problems with postgresql-devel packages on centos and building pyscopg2 from sources. For us no difference in where to get psycopg2 for tests.

Adapt tests for centos7 environment

---

tests/test.py

Improved test case to use configured db name for MySQL instead of default and rely only on connections of configure database instead of whole database. It helps to run tests parallely.

Improve testing connection closes for parallel test run

---

encryptor/searchable_query_filter.go
hmac/decryptor/hashQuery.go
pseudonymization/tokenizeQuery.go

Added `ChangeSearchableOperator` function and its usage used for substitution search operator during searchable encryption/ searchable tokenization.

Added change search operator func

---

decryptor/base/decryptionNotification.go
encryptor/config/encryptionSettings.go
encryptor/config/schemaStore_test.go
hmac/dataProcessor.go
tests/encryptor_configs/transparent_type_aware_decryption.yaml
tests/encryptor_configs/transparent_type_aware_decryption_postgres_with_data_type_id.yaml
tests/test.py

I found that when acra-server validates searchable hash after decryption and it failed then it skips applying `response_on_fail` option and just returns as is. It's because our searchable encryptor decrypts data as first, marks the current context as successful decryption, and then validates hash which will fail. Due to the context was marked as successful, acra-server do nothing on encoding stage because it expects valid raw value instead of returning error or default value.
In this PR were added marking context as NotDecrypted in case of failed hash validation and tests for that.
Additionally found, that our encryptor_config validations denied searchable fields with type awareness (probably because searchable encryption was added after the first introduction of type awareness) and added …

Apply type awareness actions on failure of hash validation

---

tests/test.py

Found that previously it wasn't supported properly and we haven't tests. After #605 were added support and here added tests.

Add tests for searchable encryption with NotEqual operator

---

CHANGELOG_DEV.md
cmd/acra-keys/keys/read-keys_tls_redis_test.go
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
keystore/v2/keystore/filesystem/backend/redis_tls_test.go
network/cert_verifier.go
network/crl.go
network/crl_test.go
network/ocsp.go
network/ocsp_test.go
network/tls_wrapper.go
network/tls_wrapper_test.go
network/utils.go

Here is we fix #615 issue when common flags for all sides of communication `tls_*` (with application and database) are not applied for ocsp and crl verifiers if weren't specified `tls_ocsp_[client|database]_*`/`tls_crl_[client|database]_*` flags. With this fix should be enough to specify tls_* flags once for both sides.
with new changes. **In progress**

Use base tls flags if side-specific weren't specified

---

cmd/acra-tokens/tokens/token_storage_redis_tls_test.go

Added the missing oscp configuration flag to the failing test.

Fix test with ocsp_flag

---

tests/test.py
tests/test_common.py
tests/test_searchable_transparent_encryption.py

During synchronizing acra-ee with new changes from acra-ce I met issues with table re-declaration into the `base.metadata`. Previously all our tests were placed in the `tests/test.py` and python evaluated classes only once.
Now we have several files with test cases and `test_common.py` that have base test cases with the declaration of `encryptor_table`. In most cases, this class is evaluated only once and has all child classes in the same file, or it is imported by other classes that re-declare `encryptor_table` with `extend_existing=True` parameter for `sa.Table` statement.
If we will introduce `test_XX.py` which imports `test_type_aware.py`, which uses base test cases from `test_common.py` and some of them declare `encryptor_config` on the class level then we should add …

Declare tables on object level instead of class level

---

cmd/acra-rollback/acra-rollback.go
network/utils.go
network/utils_test.go
tests/test.py

1. Found, that tests for acra-rollback do nothing and don't check that last query returns anything before iteration:
```
result = self.engine_raw.execute(acrarollback_output_table.select())
result = result.fetchall()
for data in result:
self.assertIn(data[0], source_data)
```
And they succeed even with errors like `key 'keypair1' not found`.
So, fixed the name of keypairs and added additional check that there are anything to iterate.
2. Found, that our `GetDriverConnectionStringHost` method incorrectly parses usernames that don't look like valid `schema` for `net.URL`. So, replaced custom parsing logic to use an appropriate function from the target driver that knows how to deal with its own custom connection string. …

Fix acrarollback tests

---

cmd/acra-server/acra-server.go
configs/acra-server.yaml

Hey! 
I got a bit baffled by 'pass' which I believe means 'path' of the log file. Hope it helps!

Fix typo of log file path
