tests/Readme.md
tests/docker-compose.yml

Add docker-compose for integration tests

---

tests/test.py

wrapped sending SIGTERM signal into try/except to skip such errors because we doesn't need to handle
cases when process not exists. We should be sure that it not exists at all after `stop_process` call
Plus added one more exception message that expected by test case. Psycopg2 doesn't return any error code or something else except message so we can only check that exception message contains some pattern.

handle one more exception message

---

tests/test.py

Fix test fails on heavy loaded servers.

Increase close connection timeout

---

benchmarks/run.sh
cmd/acra_rollback/Readme.md
cmd/acra_rollback/acra_rollback.go
configs/acra_rollback.yaml
examples/golang/src/example/example.go
examples/golang/src/example_with_zone/example_with_zone.go
fuzz/fuzz.go

drop sslmode=disable from connection params

---

CHANGELOG.md
README.md

Change log added
Updated readme

pre-release: 

---

tests/Readme.md
tests/docker-compose.yml
tests/test.py

update readme and default settings to allow users to run tests with default settings

fix integration tests to run smooth & be compliant with readme

---

Makefile
docker/acra-build.dockerfile
docker/acraproxy.dockerfile
docker/acraserver.dockerfile
docker/collect_dependencies.sh

- implemented two-stage build process
- significantly reduced the size of containers
- added targets `docker` and `docker_push` into Makefile

Refactored docker images' building process

---

Makefile

branch: `stable` -> tags: `stable`, `latest`, version
branch: `master` -> tags: `master`, `current`, version

Change container tags depending on branch

---

Makefile
docker/acra-build.dockerfile
docker/acra_genkeys.dockerfile
docker/acraproxy.dockerfile

* created acra_genkeys.dockerfile
* added build commands to Makefile
* commented all dockerfiles

Created container with acra_genkeys

---

tests/test.py

added retrying to handle cases when db not up yet or overloaded in test environment

retry connect on failure

---

decryptor/mysql/column_field.go
decryptor/mysql/packet.go
decryptor/mysql/response_proxy.go
decryptor/mysql/utils.go

Fixes T541 by adding support ClientDeprecatedEOF flag and not expect EOF after column descriptions

fix protocol parsing

---

cmd/acraserver/client_session.go
cmd/acraserver/listener.go

changed log message to avoid misunderstanding

rewrite legacy log message

---

utils/version.go

update acra version

---

acra-censor/acra-censor_test.go
acra-censor/handlers/blacklist_handler.go
acra-censor/handlers/querycapture_handler.go
acra-censor/handlers/whitelist_handler.go
decryptor/mysql/column_field.go
decryptor/mysql/packet.go
decryptor/mysql/response_proxy.go
decryptor/mysql/utils.go
examples/ruby/example.rb
examples/ruby/example_with_zone.rb
logging/event_codes.go

PR fixes mysql protocol parsing, and updates ruby example to work with both MySQL and PostgreSQL.

ruby mysql examples [T633]

---

Makefile
docker/acra-build.dockerfile
docker/acra-translator.dockerfile

* Dockerfile created for AcraTranslator
* AcraTranslator included into build chain in Makefile

Added AcraTranslator to Makefile and dockerfiles

---

tests/test.py

I think some tests fail because I dropped `killall` command (by mistake *( ) that kill all instances of acra-server (thought that it's bad way and in other code it clean up processes already, but nope )
Here I more accurately kill forked process by parsing log about fork and fetch correct pid to kill (instead all in system)

kill forked process

---

.circleci/check_gofmt.sh
.circleci/check_golint.sh
.circleci/config.yml
cmd/utils.go
decryptor/base/callbacks.go
decryptor/binary/binary_decryptor.go
decryptor/mysql/column_field.go
decryptor/mysql/decryptor.go
decryptor/mysql/packet.go
decryptor/mysql/response_proxy.go
decryptor/mysql/utils.go
keystore/filesystem/server_keystore.go
network/connection_wrapper.go
network/connections.go
network/proxy.go
poison/poison.go
utils/escape_format.go
zone/utils.go

- Add comments.
- Decrease golint issues to 421.
- Add checks in CircleCI, use "450" issues as magic constant now. After fixing most of issues, I'll update this constant.

More fixing of golint issues + add check to CircleCI

---

acra-censor/acra-censor_test.go
cmd/acra-connector/acra-connector.go
cmd/acra-connector/prometheus.go
cmd/acra-server/acra-server.go
cmd/acra-server/listener.go
cmd/acra-server/prometheus.go
cmd/prometheus.go
decryptor/base/prometheus.go
decryptor/mysql/decryptor.go
decryptor/mysql/response_proxy.go
decryptor/postgresql/pg_decryptor.go

* collect metrics about connection count, time of processing connection, time of processing request/response to/from db, acrastruct decryption count
* small refactoring in acra-server. drop code duplication and move copy/paste logic to separate function

collect metrics [T662]

---

README.md

Now reading Readme should be more fun and useful: quick try Acra, then read how it works.

Update Readme: add Acra Engineering demo, re-shape blocks

---

.circleci/config.yml

* fix building golint (https://github.com/golang/lint/issues/415)

fix golint import path 

---

wrappers/ruby/activerecord_acrawriter/activerecord_acrawriter.gemspec
wrappers/ruby/activerecord_acrawriter/lib/activerecord_acrawriter.rb

* made the code more appropriate to ActiveModel structure
* corrected data flow
* added mysql2 adapter support
* fix dependencies

Add mysql support to activerecord_acrawriter gem

---

acra-censor/acra-censor_implementation.go
acra-censor/common/logging_logic.go

1) Add missing queries dumping on SIGTERM/SIGINT signal
2) Add checks if query is parsed while logging

fix censor bugs detected by integration tests

---

acrawriter.podspec
examples/objc/AcraWriterUsage.xcodeproj/project.pbxproj
examples/objc/AcraWriterUsage/AppDelegate.m
examples/objc/Podfile
examples/objc/Podfile.lock

change version requirement from strict to` ~>`

require themis pod >= 0.10.0

---

decryptor/postgresql/packet_handler.go
decryptor/postgresql/pg_decryptor_test.go
decryptor/postgresql/pg_escape_decryptor.go
tests/test.py

fix the case when last data in data row column from PostgreSQL come with empty data and server try to read 0 bytes, take io.EOF and stop processing connection due to an unexpected error in parsing packets

handle last empty column

---

decryptor/postgresql/packet_handler.go
decryptor/postgresql/pg_decryptor_test.go
decryptor/postgresql/pg_escape_decryptor.go
tests/test.py
tests/utils.py

fix the case when last data in data row column from PostgreSQL come with empty data and server try to read 0 bytes, take io.EOF and stop processing connection due to an unexpected error in parsing packets

handle last empty column (fix to master)

---

CHANGELOG.md
README.md
acra-censor/acra-censor_configuration_provider.go
configs/acra-censor.example.yaml
examples/android_java/Readme.md
tests/acra-censor_configs/acra-censor_blacklist.yaml
tests/acra-censor_configs/acra-censor_whitelist.yaml
utils/version.go

Preparations for 0.85.0:
- updated ChangeLog and Readme
- updated versions and AcraCensor configurations
- updated Android example project Readme

Acra 0.85.0 release docs

---

wrappers/ruby/acrawriter/acrawriter.gemspec
wrappers/ruby/activerecord_acrawriter/activerecord_acrawriter.gemspec

* use `rbthemis` instead of deprecated `rubythemis`
* remove unneded dependencies
* update versions

Update dependencies of ruby gems

---

docker/docker-compose.mysql-nossl-server-ssession-connector.yml
docker/docker-compose.mysql-nossl-server-ssession-connector_zonemode.yml
docker/docker-compose.mysql-nossl-server-ssl-connector.yml
docker/docker-compose.mysql-nossl-server-ssl-connector_zonemode.yml
docker/docker-compose.mysql-ssl-server-ssl-connector.yml
docker/docker-compose.mysql-ssl-server-ssl-connector_zonemode.yml
docker/docker-compose.mysql-ssl-server-ssl.yml
docker/docker-compose.mysql-ssl-server-ssl_zonemode.yml
docker/docker-compose.pgsql-nossl-server-ssession-connector.yml
docker/docker-compose.pgsql-nossl-server-ssession-connector_zonemode.yml
docker/docker-compose.pgsql-nossl-server-ssl-connector.yml
docker/docker-compose.pgsql-nossl-server-ssl-connector_zonemode.yml
docker/docker-compose.pgsql-ssl-server-ssl-connector.yml
docker/docker-compose.pgsql-ssl-server-ssl-connector_zonemode.yml
docker/docker-compose.pgsql-ssl-server-ssl.yml
docker/docker-compose.pgsql-ssl-server-ssl_zonemode.yml

Use different master key for acra-server and acra-connector

T1157: Fix ACRA_MASTER_KEY 

---

README.md

Minor update of Readme, mention field level encryption, masking and tokenization, fix links on example projects.
_This is an ongoing Readme update that reflects current state of things, nothing special going on here 😁._

Update Readme, fix links

---

.circleci/check_golint.sh
cmd/acra-rotate/acra-rotate.go
cmd/acra-rotate/dbRotation.go
cmd/acra-rotate/fileRotation.go
cmd/acra-rotate/keystore.go
cmd/acra-rotate/rotator.go
cmd/acra-rotate/zoneIdFileMap.go
cmd/prometheus.go
configs/acra-rotate.yaml
decryptor/postgresql/utils.go
decryptor/postgresql/utils_test.go
keystore/filesystem/filenames.go
keystore/filesystem/server_keystore.go
keystore/filesystem/server_keystore_test.go
sqlparser/ast_methods.go
sqlparser/dialect/mysql/dialect.go
sqlparser/dialect/mysql/quoteHandler.go
sqlparser/dialect/postgresql/quoteHandler.go
sqlparser/token.go
tests/test.py
utils/version.go

* published 1 function and 1 method from existing filesystem.KeyStore to reuse 
* extended rotator with zonemode parameter which turn on/off usage of key id as context for acrastructs

support rotation of acrastructs encrypted without zones

---

README.md

I feel really bad for starting a whole new pull request to add just a few words to a readme file (CCPA mention).

Added CCPA mention to README.md

---

README.md
cmd/acra-translator/server/server.go
decryptor/postgresql/decryptorFactory.go
decryptor/postgresql/pg_general_decryptor.go
decryptor/postgresql/proxy.go
decryptor/postgresql/proxy_test.go
encryptor/dataEncryptor_test.go
encryptor/queryDataEncryptor.go
encryptor/utils.go
encryptor/utils_test.go
keystore/filesystem/filenames.go
keystore/filesystem/server_keystore.go
network/secure_session_wrapper.go
network/tls_wrapper.go

Previously I forked new branch from lagovas/ee-updates and then that branch was merged to master
But our acra-ee has dependency to COP branch, which has small difference from master, it's extended encryptor's config https://github.com/cossacklabs/acra/blob/cop/encryptor/config/tableSchema.go#L96
So now we should merge master with fixes merge back to cop with correct config which used in acra-ee
There is no new changes from #355, just merge back.

merge master to cop

---

cmd/acra-addzone/acra-addzone.go
cmd/acra-authmanager/acra_authmanager.go
cmd/acra-connector/acra-connector.go
cmd/acra-keymaker/acra-keymaker.go
cmd/acra-migrate-keys/acra-migrate-keys.go
cmd/acra-poisonrecordmaker/acra-poisonrecordmaker.go
cmd/acra-rollback/acra-rollback.go
cmd/acra-rotate/acra-rotate.go
cmd/acra-server/acra-server.go
cmd/acra-translator/acra-translator.go
configs/acra-addzone.yaml
configs/acra-authmanager.yaml
configs/acra-connector.yaml
configs/acra-keymaker.yaml
configs/acra-migrate-keys.yaml
configs/acra-poisonrecordmaker.yaml
configs/acra-read-key.yaml
configs/acra-rollback.yaml
configs/acra-rotate.yaml
configs/acra-server.yaml
configs/acra-translator.yaml

In order to avoid unnecessary connotations, use a different wording in command-line help.

Call key store v2 "new", not experimental

---

tests/test.py

Add a simple test to verify v1 → v2 key store migration path. Since we'll be changing the key store layout, we cannot use global shared key store and have to reinvent some wheels. Let's at least make it easy to write new tests if necessary.
The tests verify that:
- we are able to put and get data before migration
- the migration itself completes successfully
- the migration keeps the data unchanged and accessible
- new data can be added after migration
We check both default and zone mode in the same test to verify that they are not getting mixed, and that both storage and zone keys are migrated.
The tests run as a part of the test matrix, so we'll test PostgreSQL/MySQL and TLS/Secure Session variations.
Since we can't use the global key store, I had to refactor the `fork_connector()` …

Test key store migration

---

tests/test.py

There is an intuitive understanding that key store location in the filesystem (its absolute path) should not affect the data stored there, allowing to move the key store to a different location and still be able to decrypt private keys. Add a test for that.

Verify key store movement

---

logging/log_formatters.go
logging/logging.go

This PR introduces additional abstraction `AcraFormatter` that is necessary for refactoring (https://github.com/cossacklabs/acra-enterprise/pull/50#discussion_r429401067)

Getter for log formatting hooks

---

decryptor/postgresql/pg_decryptor.go

Previous pull requests like #346 and #355 have merged most of the changes from EE codebase into CE. This PR merges the last bits of diffs that I have found, cleaning up some comments and removing dead code.

Merge PostgreSQL decryptor changes from Acra EE

---

README.md

fix Acra header

---

wrappers/python/setup.py

Updated python wrapper version

Updated python wrapper version

---

acra-censor/common/logging_logic_test.go
docker/ci-py-go-themis.dockerfile

* updated ci-py-go docker image that installs dependencies for integration tests
* increase sleep time for censor's tests due to failures in EE CI runs (maybe private not paid repos get less resources in comparison with open-source repos...)
p.s. updated image will be uploaded to docker hub soon

install tools for integrations tests in docker image

---

CHANGELOG_DEV.md
encryptor/config/schemaStore.go
encryptor/config/schemaStore_test.go
tests/test.py

Use AcraBlock as default crypto envelope.

Use AcraBlock as default crypto envelope

---

.circleci/integration.sh
tests/test.py

Fixes merge conflict and failed tests after my merging #486 

Update merged code

---

keystore/filesystem/server_keystore.go

I had written in #498 that renamed variable but didn't push and already merged. My fault. There is missed renaming 

Add missed in #498 renaming

---

encryptor/config/common/encryptedTypes.go
encryptor/config/encryptionSettings.go
encryptor/config/schemaStore_test.go
masking/common/patterns.go
pseudonymization/common/tokenTypes.go

* Use `Unknown` as default `data_type`
* Add unit-tests that verifies that cannot be defined `token_type` together with `data_type`
* move conversation from TokenType to EncryptedType from pseudonymization package to encryptor/config/common that responsible for EncryptedType
- [+] [Example projects and code samples] are up-to-date (in case of API changes)  …

Set default data type to unknown

---

configs/acra-addzone.yaml
configs/acra-backup.yaml
configs/acra-keymaker.yaml
configs/acra-keys.yaml
configs/acra-poisonrecordmaker.yaml
configs/acra-rollback.yaml
configs/acra-rotate.yaml
configs/acra-server.yaml
configs/acra-translator.yaml
keystore/keyloader/hashicorp/key_encryptor.go
keystore/keyloader/hashicorp/vault_cli.go
tests/test.py

Unify/add common Acra TLS flags for Vault.

Unify vault tls flags

---

README.md

update link for feedback form

---

tests/test.py

Here is the fixed merging issue after merging PR https://github.com/cossacklabs/acra/pull/612 created before zone removing but merged after that.

Remove zones after merging older pr

---

cmd/acra-rotate/acra-rotate.go

Same changes for acra-rotate that made for acra-rollback in #642 

Update parsing connection string for acra-rotate

---

CHANGELOG.md
benchmarks/config/acra-server.yaml
configs/acra-backup.yaml
configs/acra-keymaker.yaml
configs/acra-keys.yaml
configs/acra-poisonrecordmaker.yaml
configs/acra-rollback.yaml
configs/acra-rotate.yaml
configs/acra-server.yaml
configs/acra-tokens.yaml
configs/acra-translator.yaml
utils/version.go

Updated version and changelog for release of new 0.95.0 version

Pre release

---

tests/requirements.txt
tests/requirements_centos.txt
tests/test_common.py

Added updates for buildbot
